---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-smb-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: smb-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ceph-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-filesystem
