apiVersion: v1
data:
  BLAH: ENC[AES256_GCM,data:KkeDK0/Pi4o=,iv:61eVPqejgHXduArd9V5LvnmBQ1GAxyOI5Omi6GuB284=,tag:mkWZAYAXDBXCQX1aqdcg4w==,type:str]
kind: Secret
metadata:
  name: trunk-recorder-secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRFp4Wjl6bFY1MHVhLzZ6
        WlNMVTFka01QRXA1amN5bGZtcFkvVGtPdlNzCnE1VFJrSWVrdmpCTkNVZUlzMHdj
        YndYWDlpTkRuQlBZNE9OVWNIZWxrQ0UKLS0tIDlLb0hTdVFXdFcra1pHMCtORGVT
        OEYrcFQ0eWdxSTlQd0tBR1FPZ2VqNGMKJw907rkT3EpWPcVXXUV1OyAAPvoyIK9s
        NxftUiVyq5v3STjjYrWF8nKyhRaG/LwNz7riud7zuCsHON5JaNGMtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-21T19:48:43Z"
  mac: ENC[AES256_GCM,data:Nm3Yp3kKC01pCZNSUidWr1+JeIiagDyojdWNKlChN8mn5jMw7dpALCrkBN0ZkvTEl1VUaPL9AEFEKHOyaAfwM5F9quv8RiQ0xiT4KZ5FUJCg+TbvTPZ3N72jI1wfxrfuC1p2t7hTp+f+kMsqhqY/rJlKP64dVVXkJTS3RzByI+Q=,iv:3HK2W/SH2J8SN6Yq1ilLE7MVWKSBzmkKgwnkI91uxQA=,tag:ybDqi2TDYh0aT1KdsR56Dg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
