apiVersion: v1
data:
  aws-access-key-id: ENC[AES256_GCM,data:yUDUvkOgbJVNuXXHsdq/AEtT2KM+HWD2Jtx7Pg==,iv:xtr0M0fFbeHPPJjd6wsInrSQIUqXEjVCPtOSYrZLD5c=,tag:2eDQ3eNbUZtTK8Hr8NpHsg==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:d3K1MgLtSIp3Bjx1rpCjhSuppyx/nIuA9vWED2wPXWFo7SYnyIzkap7cu6ODlBKBXY6/qwUyKH0=,iv:4hdYnL8GrvV7jx5AQfhHH0to4mGIVgkcIQ0/9NINI8Y=,tag:mZ33c7wCRkvPBlu3Npi5qw==,type:str]
kind: Secret
metadata:
  name: certmanager-route53-clusterissuer-secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZVA5THFwb1lMQXhCYU5w
        WWlXUldYMHlTZHFzbUc3YUNXR09NcXpZMkhFCm41aHQrTytTYS9vMlpVT2FmREdU
        YkJ3Y215VHlpYVhGdElqUXNhMzhJNzAKLS0tIDRPdUwxMzFWQXF5b29mN29VdWlM
        WXpRaUFORjArOFJlSlNHRkVqR0FoNUkKkAXvZISKcEsZHLqVXu+Lt7DDyRwKWd7J
        eSYG1FdF49NvwexZNE502sM3tNVvAGG+aL0j1dfFRcLoYN7OyinUIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-17T08:20:41Z"
  mac: ENC[AES256_GCM,data:HtX8JOsDeRj7UB6l/KZwkoMHZH0aT4QmBwsLJdJNzHlOKr5Qv9It4Jy07i3SmxHwtOHgvOX15Sb0xDnNSQdqWXyTdY0donZchSL9eK/gNvrmJJ7+O4JIetpQjXwCe88aRhXRGpTNHcPIcMFOI5J+3DJaf/ummOyNSWU3v6ReYT8=,iv:6DidiDVPBQC3D1V99OEZkOcAY9RPssCZzFWLxhwQsiE=,tag:vJy/QvrvJsYu4DOctuMejg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
