apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:lVrK687ooDqtnZbI3ZSmJ8OhWbD7QHQRLUinA9oRxhpVnJH4ywSCrrvJjyt7x7EhXW5/FalIXA26nAcLCBNzyeE3HkZ/Hmw8,iv:xSmiu1fUNuntoUJWNmTp9ByvjwQuHI2NTYqYLGMfwX8=,tag:Eh91j0DUj4+tCY8nlaE5Vw==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlckdZNm9tVGZ5bXl5dlha
            alMxUFVMTjVaR1dRc2twQjhTSGowTXZ0REYwCkIxS0dHUHFxbE1SYTJBTmdVSHo1
            WWxLVjdxZVR4cXhrMTVKeUNSZUgyYVEKLS0tIDU2cVExTEpSRk54OHBnN3hrZlVo
            bHhhRXpoQjludzN2T01Ja1FkWDZuSkUKX7BpR3cL7y56eBcKtfInQaiMvaEXceGE
            tG+LLAPuXVLk4gGs58/kjpFUvxYFgbR/ZrNRU40llBAv1SvZOZ/HiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T16:36:33Z"
    mac: ENC[AES256_GCM,data:vfOWG53BhIoWiwjoOnrvikGxj0Zj8xYcNnCdLlHXPJVmn+xKXWOg//kH+gdDEEwHqD11YWWMJs1IdBmgfnyRYWsHWynCPqZHSXV8vrymZSokPe48E+FczDap6iOIWh2Ixlm6V6iZxVKIpl0nybn5kcgQNO/m0oq5Nq6rt1J7cZY=,iv:2aNv66/Vq1Y361SXbzg9alspHdR5cffXnMOq8ydHQR4=,tag:iUtwFXQvuCnuhEjuptNnow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
