---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transcribe-env-configmap
data:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name transcribe
  labels:
    app: *name
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.istio.io/merge-metrics: "false"
    spec:
      containers:
        - name: *name
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: transcribe-env-configmap
            - secretRef:
                name: transcribe-secret

          ports:
            - name: metrics
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: metrics
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
