apiVersion: v1
data:
  SM_POSTGRES_CONN: ENC[AES256_GCM,data:vW8v++mnC9i+HXpBVEtz4U+68rRbxpkMrZX3CqwcZogHwIhvaRLBAmRH1hL40nd/+c+VgWIKVpbE8OZ5ruza9iJv9sQGc+vCCPTigghRfCvJCS76N6s0d6vLdFBnIAi0INYY5uXgL3o=,iv:MhIhd7Efn3gFVn8jxF2bbHzVIs6Wjk8IelmuXys4zmY=,tag:jseZsge/RvO3ATTQrpVEuw==,type:str]
kind: Secret
metadata:
  name: shallenge-miner-secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOTJ0QzFnUjJTZzM1TGJZ
        MHVzUHRCWlAwSTdjYVU2aGkvaDhSK1Y0WGhJCnlMbjZlbGtyelhiNjE1L240MmUr
        SlVlZUxnQnp6S3lrRUxEZmRtdWRUaUUKLS0tIGRBa2tPMWVucnNySjg5RU53V0Yy
        Qi95ZjFOd0lFSE5hbFZxTE1KU3BycGsKv+T2u3hvfvWxPIMhsnDUe7T+L9t6w9H0
        7uSJWxF7bEOolRa0NbfCBtGFS7/kc/HtT4ImuWadaJWR7We4cpK05w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-06-15T21:41:53Z"
  mac: ENC[AES256_GCM,data:t3EEHnD0GvWg51hwNtlIFsBZFChuhnocHc2NT1Ncuf1UmQx+SOdXiFQWWrETj+vnU93TOvSXMvwmSZh3l92bX1BxS+j2qMz38Ni4CU76h/9RjjqXWs1b8NDZZ2OeU/429FP8Ib7t+JHdisYpzoBsE6Bjy+eZ2YFucDMQZGeuXDM=,iv:Z9adWQhsfmcIMkV8JG/2ZBaZ03+5G/PzfAO8dK8p6Do=,tag:bRUMELohWlg1KaxMnfiHuw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
