apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shallenge

resources:
  - ../base/
labels:
  - includeSelectors: true
    pairs:
      env: prod
      proj: shallenge-miner
patches:
  - path: api.yaml
  - path: api_secret.yaml
