---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flippydrive-data-pvc
  namespace: flippydrive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block