apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-assistant-home-assistant-0
  namespace: home-assistant
spec:
  sourcePVC: home-assistant-home-assistant-0
  trigger:
    schedule: 30 2 * * *
  restic:
    repository: restic-home-assistant-home-assistant-0
    copyMethod: Snapshot
    volumeSnapshotClassName: ceph-block
    storageClassName: ceph-block
    accessModes:
    - ReadWriteOnce
    cacheCapacity: 1Gi
    cacheStorageClassName: ceph-block
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 6
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      seccompProfile:
        type: RuntimeDefault
    moverPodLabels:
      k8s.lfp.rocks/service: volsync-mover
      k8s.lfp.rocks/version: 0.16.0
    moverResources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 1Gi
