apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars
    namespace: flux-system
type: Opaque
stringData:
    DOMAIN_COBRA_LANTERN: ENC[AES256_GCM,data:YBbeXIaaJhs8DxGIZhel+sMY9TqGr60=,iv:imXr+XSh98n88JPG8Gg49k4eeb4qC/smE4fvjIBxXKw=,tag:tzoOnr6vUda3oJXTfh0zMQ==,type:str]
    DOMAIN_CORONET_SUMMIT: ENC[AES256_GCM,data:RA5AU23XW73wPadlTvV9WfxF,iv:c9zKi9yNCrTUwhq9nxoF/1W8XqnmDaAxufaoeF4/7Ug=,tag:4UOpxG2Wr0ounLB9GosCiQ==,type:str]
    DOMAIN_COMMON_STAR: ENC[AES256_GCM,data:D+Gi5OS8MxiqqBCrErI=,iv:jzpznJvxJtGKnxkzEwEK6jporniWEmM1EgsqnFZrDWs=,tag:DwMSZfVtVw9iPstM4/QBOA==,type:str]
    DOMAIN_CORONET_YEAR: ENC[AES256_GCM,data:GwqULPNyx9JtO5f8s5Ov,iv:W8V9JbrTy+WL4S14zQD7mKTOGWDH/XWxL1W4FKBOjPs=,tag:Ubpr3U8a3X/u3rpWQ4EQ9w==,type:str]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:0I97WgFjFUmzn3KqX+Il1Zhl7I3s8aC1PM2j,iv:y3UfXEohG+lKZEdKVzvfXMsJ9i1OVDQOk8uWN32AagE=,tag:I9kqYwV6ALcpjrkSOESHbg==,type:str]
    OLYMPIC_NAS_HOST: ENC[AES256_GCM,data:gU4Sivj/G101,iv:/zVnzG3pAvee7ozR6GqHVyzfybm+Iu4vXftYTRc4F6k=,tag:juLgzFiJDkIIj/M/5UaMuQ==,type:str]
    EXTERNAL_GATEWAY_IP: ENC[AES256_GCM,data:vQbs0r+/t0m1FW8=,iv:7ky5WQ5qggjvUvBPFCJJ1bv96eqCUFt2Z3rRiIwAGsE=,tag:688yOEUkKXQ+xzqh07yF+g==,type:str]
    EXTERNAL_GATEWAY_HTTPS_IP: ENC[AES256_GCM,data:TAifDTbdYjSVQtc=,iv:wiRvVH3qejEmjt90HvNrsiiLm6+ew/Wejy5oB7VIGBc=,tag:F134Tu3KTqp+gjI9bn+1BA==,type:str]
    CILIUM_LBIPAM_START: ENC[AES256_GCM,data:uods5QN+0uPWt8o=,iv:mX3HgymIYy2uPY4egF8FOs8FEkBKvDbSMGSZ7z5/dU8=,tag:w0Yblse4c5qnU0D5aaEsOw==,type:str]
    CILIUM_LBIPAM_STOP: ENC[AES256_GCM,data:jcm32hxshH60RXI=,iv:q7lgSw5oGegrTBqdH/Xg9HztV4e3pWMs3GJ33dOZSWA=,tag:7ixwkJjBskX22lTfWoM6nw==,type:str]
    MACVLAN_SUBNET: ENC[AES256_GCM,data:vJR/oRmQpe3G/Yqw,iv:CmeAuMFE4v4uiLtxyv3qekM7e3tLcv+jUKo281jvrZ8=,tag:hQE4Qv/Th52F3tWkza+Z5Q==,type:str]
    MACVLAN_RANGE_START: ENC[AES256_GCM,data:9+406+z1/Avatjc=,iv:d6rb4hco3MlB+rrtlJLy2wEdhxNauH5zBXW/33/xCcc=,tag:+Fb0qdbXy0xJFQ32Gj/5sA==,type:str]
    MACVLAN_RANGE_END: ENC[AES256_GCM,data:2jT0stnfj/uq1Do=,iv:JMsHx+ahZTaiG609pQDSge6QA7NTQz/QyznWpEmfqBU=,tag:HgN27z9QX5flu2cROUAliw==,type:str]
    MACVLAN_GATEWAY: ENC[AES256_GCM,data:jqV4Uihu6eXH,iv:+v9b6vIc0hzFcKDX04aJdoA5yByByMHUpauO0IzW5KI=,tag:sWzvXffjzFHUUUpp7xkYNA==,type:str]
    DOMAIN_LOOKING_MARINER: ENC[AES256_GCM,data:Zyax6CIuoxMv/clNCq6XB+X12g==,iv:iv1Rua0rNuxCW8STYc18qhFNI0NwRRrINXN/vPm6j70=,tag:hp8eqkIH8WDrnSOXm948FA==,type:str]
    SUB_RUGGED_BALL: ENC[AES256_GCM,data:9lBfCPkhe0Ec,iv:lXWmxWdw9ftVf1ther73L1JCv4DynvKRp5dQ5NvIKhk=,tag:8EBshQBJAnz1/dyVndNSUw==,type:str]
    SUB_BURNING_TIDE: ENC[AES256_GCM,data:jz0v,iv:IWblIT4OLkyDnnachF1RvVADPYzm8GvM9orTOYWwvMM=,tag:3oFyRkzdDe6rEedlHRAEyw==,type:str]
    SUB_LOOKING_STAR: ENC[AES256_GCM,data:6TvZ,iv:32h5BUaCWLh1H9eqXEGEbDDAvVNiJZwm9YsRQW7hmTo=,tag:frR7KZnfMjXdyZGVPnKW/g==,type:str]
    SUB_BURNING_RANGER: ENC[AES256_GCM,data:jYHS7Ok6,iv:GEg9DPhC/ye39dl+u27FYbv9fhT/oRNUcKQ3o3ZxQhQ=,tag:A0PDN09X+1Z7fWyaQpvAYA==,type:str]
    SUB_GRANITE_KEYSTONE: ENC[AES256_GCM,data:ZRgVJA==,iv:bp41Xklf6zk1WL5X3xK8+7ubxPQiDzwjeHLCZ/5CFgk=,tag:fwZl6pJ6aAc9SgbqNJfIvA==,type:str]
    SUB_CONSTANT_MARINER: ENC[AES256_GCM,data:jWw5UbcxrBuFLolD,iv:TSPOaC+fQ52T6hqo7N7Dj2UjPCHJXF+mTVDw+oo1aYc=,tag:9U1w+Jmpn872xdz5kQKYHQ==,type:str]
    SUB_COMBAT_PILGRIM: ENC[AES256_GCM,data:16R8Y3vTkIwtr0c=,iv:2UTSKzrmdPYs8WtVK/h5fQ0oKdW1bB1/NfJlQACRvOw=,tag:SnC0hUHi2EeMmU03xU6YWw==,type:str]
    SUB_COBRA_TIDE: ENC[AES256_GCM,data:l3Q2,iv:Abtwyn/5lp0AxwkFQ4sm7m93hT/IW+iM7H71mr6uihU=,tag:ernpZCf8YXYHkwA8t53XMw==,type:str]
    SUB_SENIOR_ABLE: ENC[AES256_GCM,data:XQiDLNjShA==,iv:ipK5jU73UrwgWQ9rKgmrIafstyk9Ikh8cLkr18hDSLs=,tag:G3cSP+6/zaoYNtQh1EMoXA==,type:str]
    SUB_RUGGED_RESOLVE: ENC[AES256_GCM,data:1abSRNOWyGa0dn49At0=,iv:TXQ6xthaKdsAvCz+qO2b//5WwH+Ug8ARATbPaJ4ZRyY=,tag:grFG/wTz+MPbrBqN/saZ/Q==,type:str]
    SUB_COBRA_BALL: ENC[AES256_GCM,data:uBhTtDTV,iv:hBRDk0uQyWZons7UDZDVrpIY1s7pYBmfPA2l+7OWc+s=,tag:NfSu0fn/iYWI7I/r/uj/gQ==,type:str]
    SUB_COMPASS_QUARRY: ENC[AES256_GCM,data:cDkG2I8a,iv:TWEGh5CYYqJn4Vg2RNyS8AKuHBhYq0iKSCSXYYR4KqI=,tag:G1/KW/EFQPwOQtODyr2MYg==,type:str]
    SUB_COPPER_ANCHOR: ENC[AES256_GCM,data:Wuci2h1m,iv:RZF1OIyuQxJBiQl6/jthK9QAejBcyYVsYIgQneizmCU=,tag:IYjeK2zjBNLKr+XVOse6mA==,type:str]
    SUB_PAVE_LEDGER: ENC[AES256_GCM,data:EJh6xJhtBBwu,iv:XoIjIn3G2+EswwVPxvOtDQXxqdYSh56ffp5nGInLCh4=,tag:Ho8GyAwk61h67VztsVHUpg==,type:str]
    SUB_COPPER_SABER: ENC[AES256_GCM,data:jo8=,iv:+R7R6w8SVL4wtvjC/Dl/blK0OfaxgDxVIdLiEf/oraQ=,tag:0w68vLTm8IV68rdnhKR8/Q==,type:str]
    SUB_COMMON_LANTERN: ENC[AES256_GCM,data:ypkcKgfdVw==,iv:JffKYsX6UaLcWQPVZ0o2gpRs1EVmeJn4XMxyTyBrYH0=,tag:H3pYuxET1do5fy3Ru9TgaA==,type:str]
    SUB_ABSOLUTE_STAR: ENC[AES256_GCM,data:QeL8Bp8aZt0=,iv:IntLx7CE7CbgtJupXgtFvVIBwSw47YjxFvIsYaAcdtE=,tag:l8c2G5O228FHDUYzYJa93w==,type:str]
    SUB_RIVET_LANTERN: ENC[AES256_GCM,data:gLqFOfxUng==,iv:Dalx5Enb6FwKMLKfXn4As+uveH1FkJrqBxMpiXCoHhE=,tag:lyAChYCkrw3Es0xZT/O/oA==,type:str]
    SUB_CONSTANT_HAWK: ENC[AES256_GCM,data:GYE9SOeSUGNSuPoE8RWn,iv:oiwh4v1Kfp425BuvODaJQFnQMaN59TG5gaaGZs1iVUY=,tag:18wgY8i5xAEknd3s5fTh0Q==,type:str]
    SUB_COMMANDO_GLASS: ENC[AES256_GCM,data:R4uuO/zapZxy77s=,iv:oWshBWTmcvu0MS9OLSdX12Sv5HEOMOG85T3/RR4oI6I=,tag:Dy9nqeX8zKaZxcv+h2nnLg==,type:str]
    SUB_OPEN_ABLE: ENC[AES256_GCM,data:jIg4iys9hW5Z,iv:YX1+DdB1hXvJm9WimPWSbOeAudncCqGq8Eb4rbyVbek=,tag:HYtNFuy2eadqt6heuH1McA==,type:str]
    SUB_COMPASS_LANTERN: ENC[AES256_GCM,data:tao=,iv:3pNsDqNUElWwR3BuSPD0s5I8Gu6SSRSG5QmHS+03zno=,tag:en+QD+nAhvB8CvjM6qcGcw==,type:str]
    SUB_PRAIRIE_BEACON: ENC[AES256_GCM,data:HJ0x4g8=,iv:I1B6cnB6qgaiAlraugSOt2t1p/BzN5zBK+9xKulOtKQ=,tag:fcQg7Ct7/PT1JCqKuAqjBA==,type:str]
    SUB_CRIMSON_RANGER: ENC[AES256_GCM,data:5QI24Q==,iv:JGbM+XQluiL0k8SrwDappEVptKG6I04e2EXEWKyInrk=,tag:hAvqcEBJHEXTO6Xt3iDR2Q==,type:str]
    SUB_COMBAT_CALL: ENC[AES256_GCM,data:nBEjlMzJ,iv:SES+KhDawm5T+8RipNQaB8jf4/ZXiE/+VN6QcpUi8cM=,tag:BqDiiW0glkyQ8tJY/sjjQg==,type:str]
    SUB_SENIOR_STAR: ENC[AES256_GCM,data:1k+XIQ==,iv:5Hw3lGYw7//UwBk+1RamAFa05fiU5ObuD7SUyh8fsAE=,tag:GqMPEn1rirnYQLQDrBq7TQ==,type:str]
    SUB_NORTHERN_HARVEST: ENC[AES256_GCM,data:OIlcmDHS7tcFGzSUWSeDl1pU6xfwD6M=,iv:0HHBkq6j8bFc0jhmup6FSI4aGTIrbQZ++JqAOM77exw=,tag:mX/v9lkF0OXcT85cbJYl2g==,type:str]
    SUB_GIANT_SHIELD: ENC[AES256_GCM,data:JoWZ+AVl,iv:8rYCZjWtPMhAKJow6qLfmc93ejwTgYcVN5ynUboRuTI=,tag:Vi85hYdPmxJmHJbdVXsKzw==,type:str]
    SUB_PAVE_SOLO: ENC[AES256_GCM,data:sKsc7n1KPRm3,iv:hseGty+ZZdaNAZJQ1B+xlhOQdFIF1XV1GXYvvSb7bdY=,tag:PjSHXZW7Ito1jfKQQblVhw==,type:str]
    SUB_PRAIRIE_ABLE: ENC[AES256_GCM,data:XN9oNyBGFbKx,iv:mfoNSc0ioQdz+f97XCxlJm05lR0JqUmdfjANajunHWM=,tag:vzybXDVq+Lh34wLWs024mA==,type:str]
    SUB_LOOKING_QUARRY: ENC[AES256_GCM,data:TkG0Vcs=,iv:HT1PhdAF90u2tEzf1XX9DE2PkIDi6wi5SkmZwVGxI6o=,tag:GB8pdp/Gohvn+nDS/qoTkw==,type:str]
    SUB_STEEL_KEYSTONE: ENC[AES256_GCM,data:zUOQMG1RrQ==,iv:wi8gxH/ELWgwFaTUub3kCdHfvloIhLmpewKQErBkimA=,tag:e3k2TNVRng2wV7URe3S3Yw==,type:str]
    SUB_IRON_SENT: ENC[AES256_GCM,data:5Q13qRI=,iv:6fU6ogqnDwgaXCdfVus6awVwnixb/1antQ14Ne5v6ws=,tag:AZVIYuvJv4QeomDe7zDiFA==,type:str]
    SUB_COMMON_SENT: ENC[AES256_GCM,data:/3/oXeetxfqwyg==,iv:ZzP5bSB0bCVuxpsmVT14mlJ/kBGA6inAgdX7CJNEk4Y=,tag:vzY88/kiABtNmSdWN0exYw==,type:str]
    SUB_COPPER_FALCON: ENC[AES256_GCM,data:pVWh6g5O,iv:p5ePiTWMyK7wlCT/rVYYaTiq69FQiO0aPr8NeZ04ILA=,tag:AN6flzfhsMF7hyC1jxV+Yw==,type:str]
    SUB_NORTHERN_JOINT: ENC[AES256_GCM,data:UIIKemvWa1wnhQ==,iv:q41YnamuK/5jwtIqdTkb5LcSuNEG5CVDmPEI3Bbfs/A=,tag:u5b2ms+ZijRJ/7W84hC6gA==,type:str]
    SUB_COMMON_ACRE: ENC[AES256_GCM,data:j1IUSjdI,iv:WOEK3G1x/pax8C3errRtalgY9dCq3DSFYHbFtqBu1+c=,tag:oF0T9MhLAsQ+6nd48iAkTA==,type:str]
    SUB_RUGGED_JOINT: ENC[AES256_GCM,data:lo6+njDC,iv:wSm2lO/Luw/vKP1LpohMizwt9qD6IzjATP6wPZCdneo=,tag:410Tbaxwrqpxd0Cme1OS3Q==,type:str]
    SUB_COBRA_ORCHARD: ENC[AES256_GCM,data:t+x8bY7vQDaoEf8iyGGI6w==,iv:3h7gwAu0MmguQfHnTj/4Qlk1jwCPzEW7nCBafA9OP3s=,tag:yEfZVIRaxSx9tD3owlPkTQ==,type:str]
    SUB_CORONET_ORCHARD: ENC[AES256_GCM,data:pVpYh8A=,iv:mMPndP52wi+zz9FzYahid0AxvpYEFwUZvR9DI6uJ/tc=,tag:f+W3rjchOcjjRjuwtW+9Sg==,type:str]
    SUB_IRON_WARDEN: ENC[AES256_GCM,data:7XSUuz6mnN61,iv:bwW2LqJB2Ma3lVl+TCtTTBNKdWAO3LMLc/gQ5OEqBd8=,tag:bmcCagbjjnNBE6Z7V8natA==,type:str]
    SUB_SILVER_LANTERN: ENC[AES256_GCM,data:I/sLYwKfRfXR4hD7aCOLFX9u0RKJ3bTyBp4o+mK1,iv:yHp519AWvRFxu+QmPVRQ7k/RK27TykNM8vZ2F0zxrbc=,tag:QvODqPVA6wWxxqccP9WOAg==,type:str]
    SUB_COMPASS_HAWK: ENC[AES256_GCM,data:UZS424v3rA==,iv:jPhQyf4cns7Pz81ASVjUUB2qv1c/DMdniAj51DYfdNg=,tag:YJTzz0kBrwrGuX5S+PqwWw==,type:str]
    SUB_IRON_REACH: ENC[AES256_GCM,data:yF2+LnOkCQ==,iv:GuUetNe9CTIFM5SA/eIdRCHaFk6OS8XGC8vSR9jyAVg=,tag:YzLs29wSFJPlSLvadfsyXg==,type:str]
    SUB_RUGGED_COMET: ENC[AES256_GCM,data:+OlJ4ZVARg==,iv:aJ2hH1zs0ztOjL63TFy7FzKta9NZQ9oh6EtDra58DnY=,tag:lWbKFw1y/OJd/aJ3z9C4gA==,type:str]
    SUB_AMBER_MERIDIAN: ENC[AES256_GCM,data:4u8=,iv:lYe0HZAlBkIwuQOaI/qAFNBTFVXCp/M+jib8k21/fes=,tag:0pDrbW/yaPI1rFMWbGMjZg==,type:str]
    FORGEJO_SSH_IP: ENC[AES256_GCM,data:AGpzba++V8gnLfg=,iv:fQHqKsi2fWWQbwHzwh5Nq7Co6NBnZttyA5FUHd6Htvk=,tag:VBj4yzbzcKAGn9QGBfpzvA==,type:str]
    SUB_SILENT_HARBOR: ENC[AES256_GCM,data:UmUo7TIDpA==,iv:+upFifyIkC54WrITb6QEXTQjSIm3/GZQv8ymnqZiHrY=,tag:uTSXznHAEKi/06gDaMW0aA==,type:str]
    SUB_LFPWEATHER_MCP: ENC[AES256_GCM,data:vg3g,iv:Tuw9WhS8lm0B+Re7huv6sroJ0OzQ1iKFGLYksSqLfVI=,tag:ChLnWrZ36x9nED5RXMT3mg==,type:str]
    GRAFANA_PNP_TOKEN: ENC[AES256_GCM,data:hy0xkAfIXLnZUwUYxkBao3X0xv6a7nAd1pL/Z3eMoyKw33S5XS0kQAwMRhuwPpE+,iv:1ZKA5MM+6sdo6L730j92btkXrDKv8X4OtlVnsjPq9x4=,tag:LiV7XNxtwK+cZrYRAhYQTg==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYTVqY0JIdTBOL3UzOVcx
            ZzhBZVRrR1EyRDJDaVBtY2FnaGVGNEdvT2g0Ck1pQnNWQjlUYXBFNERsdkhZczlE
            NUs4bkZydDZYbFBkRFlRSExucXF1djgKLS0tIGFnUjBxWEF4YmkxWXBESlFHYm9F
            dzlhQ1VvbWVhS1M0UitJNEpIakRFV00K7OIxKorNGRuHE8pn2VTolz4f3VBHLdLK
            KkthxwDF+8C8R5Nl+tz2lKF2z0A48BdqCzwX5SOVTxhrbrMVT/RQqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T19:16:40Z"
    mac: ENC[AES256_GCM,data:2EuZ9mds1ACHJgcd/WI0wcWydz9vPH4MmJsCQqjR+vmf9JpoED8MGxRRCDIUu5bUJTYCdfIKFvUcdnmDb6E/kEuy+5rdSrnUUz9k3syzAiX6VGVz5cifhihjM+84KbBwriOuazFRTdhN/IBG53q9ALf6uBGtfwS5y+ZqRjKel6M=,iv:uTpltvhDoMe9xpGZtuASWtU9rKeNSMKJfpTbnYyjoWk=,tag:cR0cG7q6y+4LoSy+qTL1mg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
