---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wastebin-env-configmap
data:
  WASTEBIN_DATABASE_PATH: "/pastes/wastebin.db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name wastebin
  labels:
    app: *name
spec:
  selector:
    matchLabels:
      app: *name
  revisionHistoryLimit: 10
  replicas: 1
  template:
    metadata:
      labels:
        k8s.lfp.rocks/service: "wastebin"
        k8s.lfp.rocks/version: "latest"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: k8s.lfp.rocks/gpu
                    operator: NotIn
                    values:
                      - enabled
      containers:
        - name: *name
          image: quxfoo/wastebin:3.3.0
          volumeMounts:
            - mountPath: /pastes
              name: wastebin-pvc-volume
              subPath: "wastebin"
      volumes:
        - name: wastebin-pvc-volume
          persistentVolumeClaim:
            claimName: wastebin-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wastebin
  labels:
    app: wastebin
    service: wastebin
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8088
  selector:
    app: wastebin
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wastebin-httproute
  namespace: wastebin
spec:
  parentRefs:
    - name: external-gateway-https
      namespace: cilium-ingress
  hostnames: ["${SUB_LOOKING_QUARRY}.${DOMAIN_CORONET_SUMMIT}"]
  rules:
    - backendRefs:
        - name: wastebin
          port: 80
