---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name govee2mqtt
  labels:
    app: *name
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: *name
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: govee2mqtt-config
            - secretRef:
                name: govee2mqtt-secret
          resources:
            limits:
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "128Mi"
