# Sensitive Helm values for pgadmin4, merged via valuesFrom (deleted from inline spec.values).
# Encrypted with SOPS. Default login password — rotate before going public.
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin4-values-secret
    namespace: pgadmin
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:ZiSvfJg9lWDwJMTp2Y047BjyyCwkE6KVqA2M/A==,iv:hLkvZUfn/Cx37zOi9vLTZqsOI6iUhKWeM+i4nWL3AG8=,tag:l1zebbKMeURHpf+MWw4IyA==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UHlibFNBaFRpUGRYaUVC
            bktZZmdwZjl1bEoxUmpYRkFRdFpVSnFUNTJjCk9ZWW4yQXJEWnFwak5zUHR0TXlz
            MUVuQ3kvc253UkVXdVNZMjNKVE9VQWcKLS0tIFIwWnB4YWFZb2xYck1XaXdyR1ht
            VlFsazhRRTY4aTUwcWdsZ0RUNHkycmsKzRit+0aHQUY6+VhMfvQga64ePX5NpJiI
            1KG/U5QM0PKdn0JTUMdMoTXbHj6G1BfpEoDzyelKzfar1f7xX5PCfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T07:29:10Z"
    mac: ENC[AES256_GCM,data:I26NAvNrHuTDQbW4xrQuxZy2NNOlitSnk39/RNWiUdsuacsaeA3xbIYOHWriYG0ljV9DMAX3fHb8Zcc7tgh6YFNAvqjC/lCAaFgITxJ4HCgLL0BRTdKPfZemBK5WkTR4Nyz+wtokz0GHpS+QC637VtGdbZB8mFOhc2KIQZV2ds4=,iv:0fjIARKCZas2nyL2YmHLC9VKlC7mdWdv/1tj5SEquEI=,tag:cWZxvgLXiQ0GQo9Cras7hQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
