apiVersion: v1
kind: Secret
metadata:
    name: mcp-wsdot-secret
    namespace: mcp-wsdot
    labels:
        app: mcp-wsdot
type: Opaque
stringData:
    #ENC[AES256_GCM,data:EC/b/rbzcpAp2aW3+pd38+Za2VMjHrnVdJVjr9drl5xYov7G4CZR5O/DHzOTZve7XuHiPe8GQFQPrrU=,iv:kQVU6mzAKmJ8PQUXoRmatf91tsh3gB+dXergR9nzG2c=,tag:1ylX8ZX/LOLA4pmUX3OXog==,type:comment]
    WSDOT_API_KEY: ENC[AES256_GCM,data:wSArwB6swBqb2mCgYOtU1Bhbeppg26NIovLyVe0CRGhIspCV,iv:qqV3Bpsr9T4JxZuxxlyF41Zz5MwlrkeyqeYLsVX8jXg=,tag:Z6tUL4+qv0mROkDcYNplQQ==,type:str]
    #ENC[AES256_GCM,data:PD7A5UOPRD2wN/WoWNZ9qPhrfqvg6+CpvI3lyyebndqGP/zzG83PrVk0uVZaG8kJa8BlmNKcUSB43t7Iyhk6FREOtg==,iv:hBhNQlIYdij9wA6QH13Aj+6RUCaR615nlNQeOgke/zo=,tag:345078aRRpphOh9cJz06Sw==,type:comment]
    MCP_AUTH_TOKEN: ENC[AES256_GCM,data:wX7ewSptJeKxrLAOyUf7hZtqVAoe0H2DKy/Sx6ce0rsnT57j2ot9Yf0qdOtysume5CXVP+q45WwBlbRZkTuvwA==,iv:wKWKYIXxB5qIFIiFoJCp4i5Tea3txX07+Hjn5l/7VOA=,tag:iR+UymIcZ7xfcVZ0LT5Rhw==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbUtYcWo4QXc3a3hQTmxM
            OFVMdktUUzRWcVRCbUZzdStvcHVLalpYMjJrCkZwQmRZUUFwU29obDdiMGNUcnJ4
            ZmJFeWJORUpTbTRCK0ZlYjlZblUrMTgKLS0tIFFMZFZuZFpOdVE5TjIwR2FlZ3BE
            OERWaHFQSk1lTXplcG81VkFFRDJxelEKns6O1CxnnN4BcKQItgix9+hssZHRjrnj
            zKVhTMjCTsgmxY+1cSXsXbIW3P1rHpjGQnIEFqkBIumJZ6v1kdF/1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T05:27:58Z"
    mac: ENC[AES256_GCM,data:z4gylMpgvKcgGU5LTIZymLx2AnJ51NQJcCozOBF8wpm7Vv1tkbQ37gX/kDGztduJhb7A10yFs9QJCUf1ituMwenubpPNJ54kxOOHt8SZHHmGEYaMHjMyFoli0WdfY23R8Ie89ydhzFzS9f1cEMDJDBA7SJnLv2pnkY3YQnJ6Bo4=,iv:+gup7oyU4uksStPJklM/E1laIhJT0P03XdvZPBYvGf0=,tag:koiQ/jaEw8I5g9HEmqujqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
