apiVersion: v1
kind: Secret
metadata:
    name: homebox-env-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:VZYh+DfXHeNorFq5ctNw7lSnCRnPmCXnCeq4WK6RjBQ+IE2RRYG7dtyHV5odDNamc/M2H7KPBXVtuLGHxC1DXPQZnGUAqFMI2A==,iv:gMZHqbi3p6AXW+2qEhfEHW3OaLvOAkbI0sqECmuiMFQ=,tag:7kKeGMa19otenX8fVvlcCQ==,type:comment]
    #ENC[AES256_GCM,data:scq8BI2Uz7yqPhFagGCNvtGjnO3csTnuL7hPypDkEkBYxCKurMl/dFfkwy+DfZyD1BR8f1plTC8mZD/M9FY3tQ30zeGWGg==,iv:6c+/RUay6n5YXbx0h5pRrEGd5eUFIjF2zK173NrffkA=,tag:8L68EVXP1R5trD9nQ227kw==,type:comment]
    #ENC[AES256_GCM,data:+80u7tuREIanmef+NIIp59sLE8eh3zxCbqbAnYToOLhkLMpRo/4MrPsSruMk1eomYF4=,iv:KmjuB1JX3KxCbOPSJjqLptveW3cV7YtO2vSGd8RRYlI=,tag:Hp+vVF06D5yJt+5CPMbT7Q==,type:comment]
    HBOX_AUTH_API_KEY_PEPPER: ENC[AES256_GCM,data:gmEbp/Vbk4avibQv2C9gS5LNDRr2i+lq9XA6vE7kGv7ahGcahTh2t4B3OrSd4nKUTYBWM11bragn8UGAzzIRiA==,iv:Xm08/fMc3bDhTpyOPcqztqm/8HdCiYHnFI1poDzQUKQ=,tag:mew83t2xviFhNw5l+b66Qg==,type:str]
    #ENC[AES256_GCM,data:nexwWIuyII/4SvTn0DuaXLOci0TUawXuO60kfA1Mc706cSgKSexHQR9gEF7vTGLHLD5Ll5GuleD48VJ4gJMJXCj2+fS6yZQ=,iv:L9748YsBlBJSGzU/p8cwaFng4xWwvdLJcijdJOhPpbI=,tag:piD3wD5hiqzAjsTqr1/qKw==,type:comment]
    #ENC[AES256_GCM,data:uO8yeWz/cHysre+tMlROOGPL+WDOAJOhgC3RUv+6kVnqsfK5HYcqXDqy9xJzCYiXsf9axZYlamHZqRdFbR9LbQzS/M50kmcAAg==,iv:R5aCqUz5PVhng5t50hrKE/U6CJKwCyy6c83DO+4jWsQ=,tag:i2yIisZn1ostfT3he2Dw1Q==,type:comment]
    #ENC[AES256_GCM,data:IxUVexommDxqeT1JTX9CS70O/YUWVzEmNPCAuxohJ89CcA7ATkZQCgs8YqsatwPRgqYq+/0zetcIV5n2aDULIvc=,iv:eCn6mIzZgrHgVUmwj4VhQNGpY4ZvCA/s5zVRm5LCtLA=,tag:S6Pa2pxZ3Ct1C/8dW/T8sg==,type:comment]
    HBOX_OIDC_CLIENT_ID: ENC[AES256_GCM,data:nBVG+ihhb75rUQ==,iv:8KeUEj1iGIBv5+vFDvsCZMbvCL+dyROUpOJacboO4Yk=,tag:0Eio5FmlaqFRig3ZP/MU3A==,type:str]
    HBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:B8Z3Zo2xpM75sg==,iv:YkcS2iLSRYd5xiUk+ixCtcQ5+g0Lc2HWZ3iugbqQx2c=,tag:Bn7D3WMrx38dHx2IIZq3pA==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR0FiMXdPbjRCSXdha3Zk
            N2x5S2NuTjdBRVp5WTg4eDc4U0ZGSHRmaUM0CkxaNE1nT3JnZFlZYVdOUFpPckdJ
            dU1GaVJqWWlOeGQ0Z3RHaE1RcmpnQjgKLS0tIFM3RUtKdmExYUFMNDR2T2syMWdB
            am9MMnEyTi9SRzBTQ1VRVFFWd2pnZVUKJlzVgD0qwcl3QtUHr30FRV7u3+1XP1rZ
            U/Nd7Y8rI0a3DsaXFok9ONmxzwq1o3Hw9u+8HTqYdKwETEH2HIOLaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T18:09:42Z"
    mac: ENC[AES256_GCM,data:09nI0WoK8tSLJcpZzfMNZEN3zTeCt4ihk45S6lWOH6y+Pc00N83FK9qeuQhRbkqnrX3bPvhJtstKQcL5xXTEqs/6n/YeYcrmSsdcqV8b/1PV/9NG6SDl4fAt4vwbtT6cJr1iL5HZ6GaHExtEpRbLGNkezmio94EH6cbYpouj0rE=,iv:cvsTZqBd6RiNaSZ8OjPp6SQa7sCkjkPbPFbZe4N5R9Q=,tag:PPMvYLe7HzljScSOjKxCIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
