apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - helmrelease.yaml
  - storageclass.yaml
  - smb-secret.yaml
  - synology-smb-secret.yaml
configMapGenerator:
  - name: csi-driver-smb-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
