apiVersion: v1
kind: Secret
metadata:
    name: smb-credentials
data:
    username: ENC[AES256_GCM,data:ndlIpP8IiHtrzXRs+5PU0w==,iv:eZCIdYjpQPXAshnPkkrlJ8iDrFzzL6ChPMMT0sggSEA=,tag:pbqzFQufCPoGTcrsdbw9ag==,type:str]
    password: ENC[AES256_GCM,data:BKMncKlLk09JcMut2DioZOyQ622lwZFyrsEjRQ==,iv:+dx4kLBraBblznVOHNTpN28RfO3rgRgaoTb0j0wEcEk=,tag:8/dogxCdV+vTO9EhTx/bow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbUxjcDVpTGJnNnpjdTB3
              NUpndURNQ2g0YzFybDM5MTh6eFc1TmFGdGhRCjhQM3ZwalBHUzAwb3djRHlVWUh4
              azJ3aVRaSkpNM01vOHpLODZscE5GcEEKLS0tIDdrSFJoMDdGOFlEYWFWcFVJWmp5
              ZzY4WlhPaGtOYnFrMWxjSVh5N2JNaE0KAx2IRyURdBsKzCbWLgQHFxewAZT0wl/J
              RrO7FqRNcW7KEZhZ1L+qWeL8+/NrhuMR3Zx85Y5NneC3jYJVrZMOPQ==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T19:46:20Z"
    mac: ENC[AES256_GCM,data:Pn9Dcbd2+UmbeTv9gBEmU9o6Y8heMn/67dHpX8930j1wu77Ngim7uydA29m7dbPrM9iS4j2piSTom0grZYPCgbxhZGTeU3evVq/BW12MWZyIh0Jp2djvUUEseNBU2Tj+aaP1uh3JWB6fzdoFhjx8ao+i7V+B7iQwVUlzhDUudeU=,iv:4JJ77jyk14RXK5v1vvYGAjPN3i6MnLcUZM1eORqj6Mc=,tag:9jhX+e2ujVjXR4wz9AxChQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
