apiVersion: v1
kind: Secret
metadata:
  name: synology-smb-credentials
data:
  username: ENC[AES256_GCM,data:keVgz0GT7ZajBJcKgjN3CA==,iv:oUC7QNq+W7esqKqi++51if8F8QbPnVDONSfLmGbC05w=,tag:bPocm7wEq51IKaWjRed3ww==,type:str]
  password: ENC[AES256_GCM,data:FR1BS3dz8Sb8vn0W1V3P25iuDmd9G2vGAknuzQ==,iv:Ybfo2AvwGDko1/VlbqtAtvLDIxWxTYev3kz8mWYukbI=,tag:vvqYTPXyOHbU+yxssAtatQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdHFMVm0wRi9yVGlNNk1D
        ZFFHUm1RdjhPYmJpVjREQThqd1laejRMYUhRCkxYQ3ZSaXRwZ1llRHdLQzVISEpV
        UW9wWE9id0E1cnBHM1hxeWJESmIzK2cKLS0tIE5lM1pXc2JuQ3AyNjJMaytLdHNC
        a1REU1hRdHBieUhUVlhYR0c0bkhxaGcKy0GOtud8MgAHigCL4VZ8hpQKMrJnTfNt
        SWdmszrIpEpb6Fja9rrVlSPVQJuk2lZq4/MOzmK2srwEycLyxg+Cmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-12T05:21:56Z"
  mac: ENC[AES256_GCM,data:cX6kp5XnyONdKJIGXiZB2E0CUz1MIX7V4SzHLsdLGDBKLGAQ/ha9XAIZVnPS9bvldtTb+9890rGYlePIQE30Kp70dkz0tMlrAeWENkQcYs6GBSnsfx916bpXQq/3FetXIa2MLfwbSEDgvwIp3/yE6z9UI51hEfr7arBVncT8lJ0=,iv:NT/2hpaEToXlcHUUqSzxaNx7QHdH21UxS849Mf6T0Yg=,tag:pe9EcsSbIVO8nc2CkCaN+w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
