---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: solar-pi-shared-infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers/shared
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-vars
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: solar-pi-infra-controllers
#   namespace: flux-system
# spec:
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/controllers/solar-pi
#   prune: true
#   wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: solar-pi-infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: solar-pi-shared-infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs/solar-pi
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-vars
