apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: weatherlinklive

resources:
  - ../base/
  - secret.sops.yaml
labels:
  - includeSelectors: true
    pairs:
      env: prod
      proj: weatherlinklive-timescaledb-inserter
patches:
  - path: api.yaml
