# Database connection string (contains credentials) for the weatherlink inserter.
# Injected into the deployment via envFrom (secretRef). Encrypted with SOPS.
apiVersion: v1
kind: Secret
metadata:
    name: weatherlinklive-timescaledb-inserter-env-secret
type: Opaque
stringData:
    WLLTSDBI_TIMESCALE_CONN_STRING: ENC[AES256_GCM,data:Z47EmbZpYgWFTZDgIp99wYsBcvd1DEbwEgfVYdunJydtggmkiBWs,iv:Dnq4ELYMFBJjvWH4H2gdKq3KwFwMuErh8KHB4ySRSDk=,tag:9WSl+yUEeklK/5ZaZgydog==,type:str]
    WLLTSDBI_WEATHERLINKLIVE_HOST: ENC[AES256_GCM,data:nCWQP07kAN5Afg==,iv:9mfuahWBA7hax7JGQjAhXl7monZzgxumdNmQmMHQSQI=,tag:B1LljH+pqd8ZAF0wHWsUsg==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UitwdGplWEU0Rk5nallT
            WFRIVXJJSWxZU2ptVk1aRTBqY1dwN2l3MjFRCmpDVGNRMlJEUGVrU3NEWW9xeXZP
            ek1rRGgzYmxON2RTYktNdjhrNUZlaGMKLS0tIDN0L1hldk4xV0o0QVdjL0srRHF5
            MzlZT3RaUnRXVXptbHE4M0doYjkwR28KqNa8wfTo0CUDsLb+1mdldN8A6j61c6xq
            9PGjZh4oEJMChnqDeWYgK2crzgqdJ++9dQs6WELMt7zZZOU/X/WNew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T07:48:06Z"
    mac: ENC[AES256_GCM,data:IyPz61Uhx1gdsAhV/9T+rJJlKySgMH8/JBRuo+lmee/OJ638nJlsfSyvskbvRPwnf139Zc2nQTwC7F7p6k1NnQ5HzQy2+cusRUg6eypKuGdBeSA/t22wym3rW9XH23KMvayqlXdMisJg9DNyX1yP8lxJvAqNwn0MhObDgoK5riA=,iv:iS7N5C34wqpiP2ViEs2901tLK3C7CcTr96fAifiZm0w=,tag:feIK+OTwt75i9Q3SA3s1/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
