---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ip
  namespace: alpineworks
spec:
  chart:
    spec:
      chart: ip
      sourceRef:
        kind: HelmRepository
        name: alpineworks
      version: 0.1.2
  valuesFrom:
    - kind: ConfigMap
      name: ip-values
  interval: 1m0s
