apiVersion: v1
kind: Secret
metadata:
    name: govee2mqtt-secret
    namespace: govee2mqtt
type: Opaque
data:
    #ENC[AES256_GCM,data:+yVLx0mxNNFbUdb7TEL6OsT9GWtl7RZ2m1Sk+cEKnH5fi0pKoWcmAyl7Yw0=,iv:QSxDaQbeKyNKzcbIrxOjuksekKQe4w9014getQ2vUCQ=,tag:mdzl1ewyvgfdRLNkXt+pcw==,type:comment]
    #ENC[AES256_GCM,data:vWmq1wUh5e4BGOT6QIbFY1z1yKSfyYNGtThxsUaXdCNUTTdkb4WSRAg=,iv:tys0W9PHffB6FCCsF4QM9MZN/vDHaLkk7OB+7jNrglI=,tag:P3rBlPIkn3AEFS49THSu9A==,type:comment]
    GOVEE_EMAIL: ENC[AES256_GCM,data:1BVbFoMSeZm9kPHddvlf1E6ayuvajoio2Z6rxWrfmia1sjM7,iv:n9IteqpZ7b9DSO60UVqTiseLnSKa2H6GcfMf4LBZCBM=,tag:dF6MtYPdjS/1I/UVlGGaJQ==,type:str]
    GOVEE_PASSWORD: ENC[AES256_GCM,data:apR5fg2eOOcl2BBXC1vNlRlpFhVPQxbt,iv:3Pp/s6mB/R8PoONyaPuy37p3dO93hA2qkAS046SCB0o=,tag:TjyCzfaacHRCNXIwxVBApg==,type:str]
    #ENC[AES256_GCM,data:Hz6MkJ0WpQb5Nganbl8c/UzZY/a85AKT8pqte6QXV+bsiQ==,iv:hYO/rWSAHd8kVbuSrsntpVj/y6iwv7OVWmW1HAzb8tE=,tag:O9EYxTsJHmY2UrHJFIjK2A==,type:comment]
    GOVEE_API_KEY: ENC[AES256_GCM,data:zHLYRQQdZWbAfUPaHtNT6Qjwvnl/IaHb3+Fq7sQPFFsSQzNynFWxXAEXHGs375rt,iv:79l2wHAXXhYLBqcY4Hwy+3WGOSMn0Zjwq3ymUiFj8FY=,tag:+QDxsZVngLjSswfdh7Rmjg==,type:str]
    #ENC[AES256_GCM,data:yuKS/Ym6V8K0NHdgCNHQ0ob/Cb7bhag18ucBvCeK,iv:1zXU+gj8h6AtCHxkocSJ6niwTA4M5/1MzzkKUkFTdzg=,tag:fbiZXiyUqC3MDW+bX8prtw==,type:comment]
    #ENC[AES256_GCM,data:irxZ1d9HBKV9dDmzC8lWGlWYpxDjrGpDRYYNfj1dyMcqWwSHlHrxz3FJ4Hrjdqq6,iv:gLDgPznmvU1t5j9jK7+wvwJRqc6WTXZIxfTgyw8wcwc=,tag:P91qipxSwF2Q0pj1WfE4FA==,type:comment]
    GOVEE_MQTT_USER: ""
    #ENC[AES256_GCM,data:2FUe/MgnYFSmjgGkgFC93YDHfFo5TIo3Wa1zNJeYL+z2SpcGDk7i6OQOMG7opK1o,iv:roLWClqyhVKbv6TWpTGkW9BZbGPHfMss4qL+uFE9fjI=,tag:kDxsDwPXeASq9jJl6GsrJg==,type:comment]
    GOVEE_MQTT_PASSWORD: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MUF4V0Q1RFlPdHRoSXBS
              Uk5Ib1JWNXVqNnV0NVlOUVNjbUtoQmJyQkNjCm5EYTJUcnZrNEZPWVpyS244b0li
              UGphVnJ4bzZjc0t3eXJ5NThVZThnTlEKLS0tIDBoMElBemVmekV6TlVWdGlyUjIz
              cmUyWXlFQnRXNXE4L0VHSVRMTHNtWVkK+gICyTpIUJJcMkrGFwRuWDNrYLEMPOFY
              wg+1qsO3bOexV12Q1kAGTOxkE7EftnHCbmqp0iG2SraBBsg22gQ0wA==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T00:51:55Z"
    mac: ENC[AES256_GCM,data:mLZaOLaBBSxwii5bbCms5bog3RmlGIvlb8zqHQKdhntx09CFZWnZx2P+RdPnVr3XpG8/eVsRbJKEBkrzKHcYTpGVShxXInr11jVHqHx/lNlBd0w11p3lncJO3V+RIYTqPSBqG7oM5GkacK143VY5I4TuSDZxWTIC42dhUX1Pahw=,iv:Zp45chG9xrlHuM7r+Yfrk+FavzN1i006yWdoRUcAQBA=,tag:mlCJTi3rgvC4i48yiDEvZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
