apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
  - helmrelease.yaml
  - dragonfly.yaml
  - postgres.yaml
  - values-secret.sops.yaml
configMapGenerator:
  - name: forgejo-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml