# Sensitive Helm values for forgejo, merged into the HelmRelease via valuesFrom
# (after the public forgejo-values ConfigMap, so these override). Encrypted with SOPS.
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-values-secret
    namespace: forgejo
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:NaUJ2bkUrall4EpWtYS2LKpIQV90PIqkimx+cu5pnEBpNZBto03ysNkn1tEbYZwdhDxZ9w==,iv:n8QGanmCU0gyCzp2EZkNtQkHOeHwv3gt69CC/W2F3Gw=,tag:dkk77cC6sSVgSPMUHANTCQ==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNDBJYndKRDA3Z2lLMTJt
            N0I0ZjRTVUtmeWhwWWJvL0pLaUFWbWRDcTJJCml4anJWVFVHR1ZXN2VxdTdWa2xI
            MWh0RXhFUGFBbHFXSmgzUk01SXk4MXMKLS0tIFhEL2l0MndxUlNHUkZxTHdxelov
            NUVWVlZOVkc3NlAvM2FuMVlZOGtteFkKZ93QJiiAdHi9ZcMiyc8/fo2wT3bg04Fv
            P0u4kVS8Ks17cRjKQucm3WTp0UejPE3kaM7CyUsXt/sV2hCq56cHYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T07:19:59Z"
    mac: ENC[AES256_GCM,data:IFgigFroW8xTOmgnEysNsIxHeXkCyjCu6+TnObNQc/fpLCGZmqfQ5KHIdJadSsg3qJDlgkdSY2iWhoWcWwORlXywXnTx9oL4eLFCmy7drbmEA96FU89aDwGe8JYJXiyN588IWCY08q2W6wWNHClR+xItYaMUFx+x91bOKvB6olc=,iv:Mx4nFoVVG/huj941E7tA1aY9ZVkEGBFE4bi1UnnNGVY=,tag:kXe+L8b99rcVT0QmRKj2YA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
