apiVersion: v1
kind: Secret
metadata:
    name: forgejo-values-secret
    namespace: forgejo
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:wkTH+aeJ+oNhmSL+Fk8ZAji5YQFAHPvsI8W7JCjmhGNm1pJaiYVlXJq/AXEwEL7lr1/zXDB8KMQuy/IagBG9BCi+FpQ/YdXhubwsrh+CasZZADEjtrzwq4o/wUWjZhk=,iv:Da42wvytOkJrKqSIzGJjvFUI1enUk5btI9gDtDBQCa0=,tag:zlM6htSo7vZxIRUybTZNwA==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNGxnT21rYTQ2OWMrbzJT
            RnZwaDNTOGVNZmx3ZGJTalN4VlczWGllc0E4CmlWSHBxMlp6QS9ITkVXY2hRWUtq
            dHVjU0JnV3dUTGc1T2pnem4zWWR1UjAKLS0tIFBnTDVxUTJ5RFhNa3ovME9OWWk4
            cS9kMjdTR0RHRkNoZEo0ejVMSlcwcFEKx8MUrDQ0Kqce4P7WYnHjv7uqx5sGPqtG
            ZNdNb9A22xxS5Xw7EDEjmOUVRS+w7K6BP+iz+EJilD4QdgbWJgS0Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T18:23:59Z"
    mac: ENC[AES256_GCM,data:r7qIcsIJwPz3TP9VjZdGnXG/Fx8+gJqV/qX7OJ+iFz4+2Fwnt+oeZY/U7ArwV5vHT3MM0+eVn88XwT3LbPoEDpPefHZV6YhJuK9eCCt+t9veRoI8BsWhWZyCrT06OFn9cNcCbXvc+QVwyyCi9RouZ6HgB6DaFIKipuZ14HJCQxs=,iv:j5o3WjUZkMOjozuQeZBHm8wXsQqoFr0id/WHQKO9kS8=,tag:GPRUVP2xAObqtpv60woHrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
