apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secrets
    namespace: openwebui
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:+gKeyCX5Q9U5Bt1ZADiwJ1vvakNzsgOEpr2EV+qZLcJgFC5XKcTP1mRGDnIcd7oUFOaBrwHkYMwpIZtMMAaqD8GceVfRYGlg,iv:gnPufsCA89sk7YzJTVlk3rQ7iB/oB+eFTaO8udyeJ1k=,tag:xIJW2IpACWmRky7qNZ2Gjw==,type:str]
    client-secret: ENC[AES256_GCM,data:9gR97pRcW+xdRTA4avtL64s7aNptwcucBGDmAQnrpUMjgFI=,iv:SHKUi5j9HGmGaC0V08ZSmEdocShPYzQoSzBccry+4tQ=,tag:j96wBS+YEXhG3RnmvgR8bg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:BF7HvWNNqAtD9sFUr7hehGjrRXZ8dQb24kJsTgUAA4UPJudDATS2ZpevzfY=,iv:jdsrNsnMbhgTRP6VSZHVGkB6T0yfXnhrUcncmNI4Dto=,tag:u2PhnofBO0mTHMfWpGKPWw==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbDBwVmxjMmE2VU9OSkdo
              ZGRKbWs0UnpHNDdjS3VGajFVaUF5Tk55ZUdBCmQ1YS92c0xhUGxNZ2dCZ3ZvQjB0
              a2ZZZWRkb1V3eEFHc2pnUUJLenM2elEKLS0tIEtoa3ExTWlpaklqMGZ2MFNFakRS
              WFd5eEUyNnE1Mm03ZnArSWlJcEhtZ1kKY7oA3jwrgnchzL+eVGFHHNNj+1OMOR1J
              AHXe6ZLq54vOwhnMXw39dxKnI4hbSQGACUoU2JDIJCweG4UPbNyqpw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T23:14:57Z"
    mac: ENC[AES256_GCM,data:/kGim3PwcXIAfHfURV03u2o9ZvZyVh6825H55ULp2johDcdw2EabWFzhOhh2/UeT6cx9ND6s5sPRZBbbjKHBMnn/ruMi9Lxy4kCUyeEnMnB4u7UztqHkw0wxNy6+QvQa4cgF8LOPQuzt/fELMHe4QQqyFjZMWmFqFL2VF++2Oes=,iv:WgpcpO9r57C1OgJKn7/fB79SWAa6Ebgu3uqjaBWPiKI=,tag:ukY6OwbXZP5MrbN4FZNYnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
