apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-emails
    namespace: openwebui
type: Opaque
stringData:
    authenticated-emails.txt: ENC[AES256_GCM,data:JIeILWDtX0WHAtZ5L8/cklSogVIYVwP1pbCcGA==,iv:4Vw4GqOlJhkjJEvM5r7S+d2hAuBMYWKR+R+7P81YZu8=,tag:JwLxr270bLNt/vjOByloWA==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NDFEZHhoQkdHMDFjMmJB
            Q3pET1JNT2RSMnhDcmRCY0pnQUNzdmJFNm1BCnc1KzZnYitLT1c4bUxIT0pTcmVF
            ZnUxSHUzbm02ZXNoVUo0M1RJTnN4Yk0KLS0tIFloL3NsRVYyNER5KytyOVlQNjU0
            RVpzSVYwSkFvY1g0TTdoWGlEQlc0WE0K4gauOTWn+ynutfl9/9mhdaPVusazKT8W
            HTtvLMzPy45ZCxLq3Pwk1x0Cz4FbRCegsDVf16MWbSUySN4szfcHlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T08:02:23Z"
    mac: ENC[AES256_GCM,data:tMAjvU7bkvUbaO+kOXsmEJx/TYLqBblO1HCNsMVbbuOXttL2psSBnevxBMoBjg01UV+s/iGbWt4UNouyPyL9oV5FSF7tLCy3gELHPzZqhPbFZPIKrrwrZn1LZtxch+Mz1exQiZFUU6eFiklzh6sPuXllllyamrTrSLvmGv5R8sI=,iv:+eM2lIrxxQtnXwWODBIsu9WWlPSohXMSVluk+JjzqRw=,tag:/k5uf78GmZ3+zJtzUCPYhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
