namespace: wastebin

resources:
  - api.yaml
  - persistentvolume.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      proj: wastebin
