---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pnp-deliverer-env-configmap
data:
  LOG_LEVEL: info
  METRICS_ENABLED: "true"
  METRICS_PORT: "8081"
  PULSAR_SERVICE_URL: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
  PULSAR_TOPIC: persistent://public/default/notifications
  PULSAR_SUBSCRIPTION: notifications-deliverer
  PULSAR_ENCRYPTION_KEY_DIR: /run/secrets/pulsar-keys
  PROVIDER: pushover
  DELIVERER_CONCURRENCY: "16"
  DELIVERER_RETRY_MAX_ATTEMPTS: "5"
  DELIVERER_RETRY_INITIAL_BACKOFF: 500ms
  DELIVERER_RETRY_MAX_BACKOFF: 30s
  PUSHOVER_BASE_URL: https://api.pushover.net
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name pnp-deliverer
  labels:
    app: *name
spec:
  selector:
    matchLabels:
      app: *name
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        k8s.lfp.rocks/service: "pnp-deliverer"
        k8s.lfp.rocks/version: "v1.0.0"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: k8s.lfp.rocks/gpu
                    operator: NotIn
                    values:
                      - enabled
      containers:
        - name: *name
          image: ghcr.io/michaelpeterswa/pulsar-notifcation-pipeline/deliverer:v1.0.0
