apiVersion: v1
kind: Secret
metadata:
    name: pnp-writer-secrets
type: Opaque
stringData:
    tokens: ENC[AES256_GCM,data:0hoFYVePz6DroMFmwi8eILT5k/KoMrYL5JQSfHbmWbvJpJ6iDRSZHPJNN0MtUTY8G0DxhatgOA4lXZW8zg7NUJvavMgOpBIyisq6QyODDmbyQ5hlJKqa6HFj9u7q/afgRNcE42BSbykp0ghPcbkRzYOnk5/4DCikf36jcWJvxcnM03sLBP3tQAMPc8WHmfhDwNcys9HM98ghoB+B9q/53q3aJ+oASlOS6bvI0z1zlzf0qrjnmfgh2d5TOEYIU9/PfWUGHUQdacTH63eHAzPgBmmp6FCUeTTUWotbl2A5OQJh5kcEHVkDhORT1oFWlhdFAsCHt510Q539K/h0LTSEF6zrEJucB9cj/g8x+PanTXfS6Zn/1HYs7X7ykLh8WAIUZrWJsJqQWehDuk23m3bK3TBz6bLyh0f5Oqil06ay5+o=,iv:ukp4RjeQWPiK+s5uTrCqOvERaXgjsXYsAcXG2XVqO1E=,tag:62VN+cGEii/jkJ8UW5pEAA==,type:str]
    v1.pub.pem: ENC[AES256_GCM,data:44VlQkySSMxJiLgBtQ4YZ48gY6wo4wNBkaAVSWiXm9EOxKgK9v0h3ymwQZU1qN5HOQt/xNbOCnEtwj1jA9OtzTKiMXDUkxXkcUiaByIAq+NyF88x3xNUMJH1Ufqi2lrru0x6N2UEAu/AWmuMT5IMj1MUiZUat893ORoQzmLNWOgO6tx77EfaBxHaEfkGp6q3+nnpnxGHXj9V5STgYCnUzSVj6fjw/wTrQbF9bMJjPx5Xr6Y9O8owrD14fb3bP7l/DyBa/TQoRrdcBRQ3hTtBV5MFxDoDfcGOFcHzWLh6nOkVMVMwwWPHeU7t69LvEuoWgr/OW27HZTWAA/mEAJWZkocXEtk1VouyYPVDQnjSTog4bDjOhs+FI+69vIcH0jyxqQ09vSaqLICpqr/YWI62YnTtLBEZ+JhPWEm8GtV9MsPPIR8WtVPDmw8M86+RD09sshWapuaAXs41UBPAdzHo7OqSjm7rZRL/VvibOCjfdoL+px01HQWvpo64C7mGW5D6wUv/DHmCeKj90/tPbKJ5Pt6qAvz/1Qeo/LeWBoYPvPs82EQZifmCMDNfQPNoRNndqXO5byp/LCvLXY2d+Py6je3dtQ==,iv:2Xa6YsUV6pFVPf1W1XW6ZnitFbDgmyNTUHCL544F6Lg=,tag:+GaLKx7fRSqHsvdrGepSjw==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZlhJSFZVOVVhK1FVLzh3
            T0ExNGlKWE5Rc2FBaktOSDAwS1E1N2NzSVNNCmpKc0dTK1d6TXZrRng0cW1ESWox
            SEsydTRveGp1bkRMWW8rN0J0MmdCaXMKLS0tIGVVV3ErOEYxRHJhTXdWUCttYThF
            bjcyd3JIYksxRUtHMFJaVTRWSzhldWsKA4B/0jYVz3rclkMCBThBD0CUXGjcU5GC
            Konr5VBBVrDczCo9uJwoeQuC0hoFcOywAvM2lQZXwPorARpTy4fQXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T19:16:40Z"
    mac: ENC[AES256_GCM,data:evZw2KTQhw0J4Jz0u0rbrntjOSTZP9sEe3NonADQ5QA9VIHUr42z9qv63PZrZUU2SORiypoh2+FLvrskbdkIX5GT2W7fchUYRBmH56xEvvcqPeacaCX3vtX163z9jPtG7Fic2ZY4Mup95/1GUTmKFlY9aBoRr3fWHhNvPdwKBBo=,iv:s+gIpz/7WrKhtsgWzrg2DjlfFq9Iif9cBI985nXaN/g=,tag:jYXl4QjOTiaMj/tq7ohY5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
