apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: r53u2

resources:
  - ../base/
labels:
  - includeSelectors: true
    pairs:
      env: prod
      proj: r53u2
patches:
  - path: deployment.yaml
  - path: configmap.yaml
  - path: secret.yaml
