apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:rjg4FYr6zrl4TpGVhTKbwrAyZrHKe16h4l6TLQ==,iv:6lfINr/UhMdUnb6J0TqPT/++NNVOG0QjVimj/4OFcGI=,tag:9yf0JWXwi5iL+y9pxAzmjg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IZ/SG5bsxz3JoltGhXX4ph06BEag0ApbPBg7E2FSBv27NeywDsPcUH2dwN1hKzLbclDAtGkbjbQ=,iv:5A4nE3+xtYIlPpfyNzxMDNbKG0vOadj3pBcdyyMSZwM=,tag:nev1a1/uhMqYR4ET+HTlsA==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:WasSH+0gyKxYjLBa,iv:aL00xXCbdNl0nROFUaYyS4BKVp/5kC4T+CVUrVY0NVg=,tag:sXW4dL1MuF+QsFzF+norDQ==,type:str]
kind: Secret
metadata:
    name: r53u2-env-secret
stringData:
    DOMAINS: ENC[AES256_GCM,data:87I3Qyf00dXiYsg8D1Mi886j+/5opStMdeuV+hLL30ZfGNPKac5mjArxUjvFEmBx8aA1ncNJx9AznE2JybWrowIwG4dq3xAE3oRYNvE4UfKvmywRLxt1w7shgXdtt6fqRcUjgxFHdAHOTNOWrvrOefZcW0UsMhcoARtmRAeQgmj1meylP0dT4iJwFthi477BSUQVYSOmKDKUeqdgnXD+g9uCdWJc,iv:0njKTV6E7xfEXOQUq/8cgtNr2oS15AF5JoTzVCd7Q8w=,tag:GRIGE1nxDXsal67+nqhj/g==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSER0ajJXSGx5YXRoWVEv
            UEFweklrTzhGZEc4VDdKN2pRZlNZVzhOVlhJCmJHek15SEZZTk5nOEhpNEpKVkE3
            MEpDbkZabUlSbVYzR1JBUXNycEg4ejgKLS0tIE1rdTJyelExZXVSd0RiM29ocWFh
            SG1MYXNoY0FDbVJNbXZxeldIOS9YeVkKXdETGio7FkOkSnk3MtIvsIEWrRdPm3VS
            vwK/TKWJS1mwIMKDGRhOCm+RVhtT3OESdVU0ZAlyheXroXwFyx7d5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T07:48:06Z"
    mac: ENC[AES256_GCM,data:S8I3uDwCl89rlZJZ/Z2QcZC+ik/iksWBlIb6cn+cPCVu0LLHhk+LGOjRv3OopnuiFN+YXbRXdfL/xIxdAy5xQeEcCRE4MdCFRowrhOAsbYMgOPfHWlEO41ZdW6yABMA1Gt/lOSxPN6lrszEk0giMp4V8wmuTcMAvD8EU0srnIBA=,iv:O2RQi0TmDTvsKssUsSGKMYD2rdnqleLGpkDiPu7tpMc=,tag:tV4+BUqD/9u3BShEyftVrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
