namespace: lfpweather

resources:
  - mcp.yaml
  - mcp_hpa.yaml
  - mcp_secret.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      proj: lfpweather-mcp
