apiVersion: v1
kind: Secret
metadata:
    name: idrac-cert-idrac
type: Opaque
stringData:
    IDRAC_HOST: ENC[AES256_GCM,data:BdWBqBd0czQ=,iv:4aY3Fa7gz6rcRrYhqIe1RX0HiEoIsXzVIuuz1OLdlV0=,tag:ObsjfLIm9jsL8Nbvjx6m7Q==,type:str]
    IDRAC_USER: ENC[AES256_GCM,data:+guw2A==,iv:nUmcXZ7iS8ATXFhkuij/3Pa78lAthjjYTaf+0Qnxs/A=,tag:nIzjI/z2LX8thvH40pLq3Q==,type:str]
    IDRAC_PASSWORD: ENC[AES256_GCM,data:nQ2/NgSOT+WKzQ==,iv:4qxMyhWCl1vzemR0856Kf9+dTQAdUSWVZYlH5SwbWI8=,tag:Mujz/1sOUuJeM5Y25hlCkg==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVndEQXFxSElaODJOKzBS
            SGJFNWdVTXNKSXdrL1JGMjZhOU0rMTgwM213Ci93SDl6aEhwRFp1U0RTOHIyclI5
            TVFOeWlDNXBZZW9tMmp1THdGSEN5dzQKLS0tIDNwelFncnFlMk9ZY0VHejd1Mk5O
            MjNOc0JXUFhNWWRrbnM4Z2xCUTdFRjgKEgvRxmJhAf60XMISrsjPj5baQqGaefi9
            d/PuInoqyOwyjGWC0lN4s4jlsmQYDE8H2yHURkC7nxaBpVlxA/1gvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T16:43:10Z"
    mac: ENC[AES256_GCM,data:BNy5h9OQqSaMiCKu8EkWxFDX3YHw+T7IKjdmX+YhVV5/FOJiat9YcChUs4vyFTRcFiQnBwKwi4pyS3OHfofq63iAFor7vJL9jQyFJX5x72mqNxHOUKGLylFEUo7jYut9TN8R4M6ZchrXDvLLBmlKNsYbgzhN8ap8UjSe+5A1iUQ=,iv:VCT3RAAytpe3o1BcMgWVcPtayUUcXCL1hXC2EFL4Ycs=,tag:rxRAk2Wo0+Spd5AWLp5Zmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
