apiVersion: v1
kind: Secret
metadata:
    name: idrac-cert-idrac
type: Opaque
stringData:
    IDRAC_HOST: ENC[AES256_GCM,data:BdWBqBd0czQ=,iv:4aY3Fa7gz6rcRrYhqIe1RX0HiEoIsXzVIuuz1OLdlV0=,tag:ObsjfLIm9jsL8Nbvjx6m7Q==,type:str]
    IDRAC_USER: ENC[AES256_GCM,data:+guw2A==,iv:nUmcXZ7iS8ATXFhkuij/3Pa78lAthjjYTaf+0Qnxs/A=,tag:nIzjI/z2LX8thvH40pLq3Q==,type:str]
    IDRAC_PASSWORD: ENC[AES256_GCM,data:YXhTV2n7Va9l4BW/6StRXC7uYrQ=,iv:OjV5GOPsSJzKkWo+jUvekCQWh/pEfPvocYEZ2qYgJf8=,tag:KBqAHlYqdbuILfwRh6PdMA==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVndEQXFxSElaODJOKzBS
            SGJFNWdVTXNKSXdrL1JGMjZhOU0rMTgwM213Ci93SDl6aEhwRFp1U0RTOHIyclI5
            TVFOeWlDNXBZZW9tMmp1THdGSEN5dzQKLS0tIDNwelFncnFlMk9ZY0VHejd1Mk5O
            MjNOc0JXUFhNWWRrbnM4Z2xCUTdFRjgKEgvRxmJhAf60XMISrsjPj5baQqGaefi9
            d/PuInoqyOwyjGWC0lN4s4jlsmQYDE8H2yHURkC7nxaBpVlxA/1gvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T16:46:06Z"
    mac: ENC[AES256_GCM,data:BvyCUmlNMr29Hw1A46mNd8I8svvLo4xnhknrjS/3tAhKnKgs6Bq+buQ6TUUwsHPzUd2miqHBlDy8QOhekg3EovpDTpNgWnBxxZoqi6zh6n/sN81Xgd8eLC2cOqCIOmHxGaQ5wr7XnvUaQBCAxAJsph5U29oit8siRxjF7jYub4s=,iv:yh9JGTmPbHeouxgdXp5umOV8LaHuqu116jWi3qFkd3Y=,tag:sLDU1zqUnN2w8WLyJWqfDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
