apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - gateways.yaml
  - hubble-httproute.yaml
  - multuscni.yaml
  - cni-plugins.yaml
  - multus-macvlan-eno1.yaml
  - multus-macvlan-enp5s0.yaml
