apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-env-secret
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:oAHv5PL9GRSl2aR8DGwj2OooPpmZhh8YgSBKka9M7L03hbsfVanPpwZvUFg=,iv:pTVMwy80hAb6jXxQSVwq9bKK7fsKWQfTwQA4jQjGU+o=,tag:qzQZ8lSEzN5LSSoehq8itw==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMWVOTFlLU1pqSkcvU0l4
            NDcrUUFpOEhkQXZSWVdaMlNOR3VxMjRkNkJjCkdBdEdXdE1seWFWRjFlN1BmWVBw
            eHloeUNzR01HUEhYUzNVeGhwSjRGOUUKLS0tIDl4N21YMFJFSWlWdmF5WlZjNy9K
            SDN1eFFHZUgzTklPek9rRDNwSDVPS28KdG207Nvv0KuMpaQS7pLEWu5W7nJzMhtG
            RKpGPOPCh2Y0edm/Ob8PH7OJEwWj7BSqtulEuKi0hksyL8KESEpxNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T04:39:46Z"
    mac: ENC[AES256_GCM,data:KWPzTWW0svYs4mxhlRI9xep4U8cv7r8Z3p7iJBMl6LeD8XNYJCFNLmj9/VjUNbyMKzMoibnjp9/i2uyFp+6Bs9jqY44bbrDcTLhhBEJ1WQ+DeydcfJQF/8rvYKvN774EMqHZTITK0AWCSIJ6U/yjCICS0jGpYcNvxeWyApX6ack=,iv:xCOwM7dK+691UasdHOgxOzeur4tNUXfcWSzICwFtJqk=,tag:s5uYO10hr4XGj9pzbkI3vQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
