apiVersion: v1
kind: Secret
metadata:
    name: lfpweather-frontend-env-secret
data:
    API_BASE_URL: ENC[AES256_GCM,data:tfBhYq+97ykLg6hqcxXEdLc+h4nSNVlDrluqjDUAqhNfsiKAi84pK6gQnMnCAryQviD4jAN/ldB8C9miYN76PYxCIhs=,iv:bgyUDCxemHTUhhS2lW2sUQaswXLvRqsCh9wXmOVrTII=,tag:e0oW4BAit+EevW4B8tdybw==,type:str]
    API_KEY: ENC[AES256_GCM,data:2GSemUbjYulsRlnt7UkawwaW+r22wEcUAAE/4j7+5nUAiVpFTbRKpbqYTT4=,iv:dbtBkCt4H2h+fJ9+n2mfCZ9qAkNNqASJH9ytRwpn1yA=,tag:AlmDQbn4lpd4h3KKWtZoKQ==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMSs0NnJFMXF5anJUaGJ0
            RzBaOGJxSThuT3k1VGJBa2h3TFhJK2dTT2t3CkZ3T1QyYk13SGJCTVNBYmM4NDJl
            YWJUS2lOaEVrQ0FkYUJ0eENLSGJmeDgKLS0tIEptdDlwc09leXhObUZvc2ppbERC
            UzhhMWVlclNmU2hRbXpqM0dUTFd4ZGMKRnlVOt70DHH4fwT2afRHav9hKnKsipN9
            dcdHmohSwtz0jUP2LD0BtniEe2YKP0mI6yrnP2tam3rlK7eBF1zeRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T17:17:17Z"
    mac: ENC[AES256_GCM,data:ZwYTvibpy/0yS/xt3IKQmP4Z9KajR3hrB7DpZ91tg0Yw8UKPsHodwe09fxOr0OFwcK9719zk60WYZQCcxYkkWXpLrkcA10NNAA2L4R0SlIw547eOVfbKjiUw8ZN5W6EvjNTA9FouUMHMv+os/IHjeoddnFFj5ZeNFcYv4/rSa9g=,iv:XzD09x6aTRXbf/Gq8GTgAkjt+HS6lSnOVclMkKgUZ08=,tag:kDBpLX/49cjjWNhKkrBgAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
