# Ceph cluster, SMB/NFS drivers, local-path
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../configs/the-intersect/rookceph
  - ../../../configs/the-intersect/csi-driver-smb
  - ../../../configs/the-intersect/csi-driver-nfs
  - ../../../configs/the-intersect/local-path-provisioner
