apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cookcli

resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - persistentvolume.yaml
  - oauth2-proxy-config.yaml
  - oauth2-proxy-secret.yaml
  - oauth2-proxy-emails-secret.yaml

components:
  - ../../../components/oauth2-proxy

labels:
  - includeSelectors: true
    pairs:
      env: prod
      proj: cookcli
