apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secrets
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:HwGHBt7pYbdu5ZwE6FykF6HKVl6DQFntEY7rsrdne/XSKCpY,iv:YxUoq8m/x/XI+Xe6a4wZIAJx79T1bfYkfh8qOYkVxfw=,tag:1nNbshCXAzOo/Kdqy/PgZw==,type:str]
    client-secret: ENC[AES256_GCM,data:9BcSxQahuU2LyOmoasjilS6paeqlrkMqo/kpWWxe0/g=,iv:BBt9DLe0fjkv+SaNVA7VFvbXA/XJtVFee7y6ql2I+o8=,tag:AI5p81i9SCaLq8ZeAgg7Ig==,type:str]
    cookie-secret: ENC[AES256_GCM,data:qUPDM0grl+ubKcvOdQOgyhNmyHgcrsEZy9ZQiu1hcEFR4Cso8nqRbqNFvl8=,iv:WOeRdl0KpUe84WjWr/JC0zRCCE0vhMq3lIHXMKazG+o=,tag:23c9Nq3ydP4fqAo8Z0LJpA==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQUpUeTd6RDdHN200Slll
            eW4vNjduVlZoTXpiU2orZGpKM0tmNGtxNTNJClVnK3FMSkNIRzM0eEd0Y3JkZG1t
            bkUxRnFWVW5xZkdZcmxxNjNLbmZBSjQKLS0tIGRCYnNlMGdnZ1U3bEhyZkZKeEFm
            R0IvMkNXMFhtd2wzVzBwZ3lLQVp5MGMKiIUXhdrw3Yf03UuYia+mmhrBv+Yu2zb8
            EdKp/QD6UvxcW1iPAiDAYG1jdP/JPdm65y/y3EStu0HsG/WHj8gDMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T04:56:07Z"
    mac: ENC[AES256_GCM,data:bCVBf5HXNgzPjyR0uB7h04BrEJZD+FWhlpnLeugxO1IeChyAGfnj7YOWpD3ydv9nIy9dW6HMGwqDedfUoLBdCi/vmSoKBonzdp9ct1PMns9vW4y0Z4DunibqYDLQ+SXwqqEOvB70z3ALuzht7Vaq8DkelAsftlElNd5+PxG2JS4=,iv:BVi7rMeTfI8LFwvFR0ISsKigOSxNk2iapB4W7pPRZOs=,tag:OcU7L8fQ/1ZYKDWz4+c77Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
