---
apiVersion: v1
kind: Service
metadata:
  name: cookcli
  labels:
    app: cookcli
    service: cookcli
    oauth2-proxy.lfp.rocks/inject: "true"
spec:
  type: ClusterIP
  selector:
    app: cookcli
  ports:
    - name: http
      port: 80
      targetPort: http
