---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: yt-playlist-ripper-pv
  namespace: yt-playlist-ripper
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0700
    - file_mode=0700
    - uid=1001
    - gid=1001
    - noperm
    - nobrl
    - mfsymlinks
    - cache=strict
    - noserverino # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-yt-playlist-ripper-share
    volumeAttributes:
      source: "//${OLYMPIC_NAS_HOST}/media"
      csi.storage.k8s.io/node-stage-secret-name: smb-credentials
      csi.storage.k8s.io/node-stage-secret-namespace: storage
      csi.storage.k8s.io/node-publish-secret-name: smb-credentials
      csi.storage.k8s.io/node-publish-secret-namespace: storage
    nodeStageSecretRef:
      name: smb-credentials
      namespace: storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yt-playlist-ripper-pvc
  namespace: yt-playlist-ripper
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi # placeholder size, not a limit
  volumeName: yt-playlist-ripper-pv
