apiVersion: v1
kind: Secret
metadata:
    name: lfpweather-forecast-inference-api-env-secret
data:
    API_KEYS: ENC[AES256_GCM,data:0SapW/KuUr+Xex9B08LWxM516JrmcI9bD/eamPBWWxNA8cu+6RCNeAngWG4=,iv:6Jdihlfd3nz+jpnLsgavMR9qxMmr5bX+bVEz00IW1gQ=,tag:eW5iyCWanoLDVZmOANMYIQ==,type:str]
    #ENC[AES256_GCM,data:j05olxucXeZquko0xo1d6JQ+Pu7CnMjFLpKJ/8kSso/A+Eu085ECmD7QlV35fvgIm4FtC1+JWRfmWyIYPyKTtzfGbIdFJ8fwczCowJ59SyTNk2demQ8MFk+Yp2FX3Xg/edGhLo/2wIAcwwqGhE5+/8ShFxElsHz40pQ2MIo2q1M=,iv:2JNrpWmfy4NlA4PhhJpMfOxB41H/ffXPzFr67S9YcxQ=,tag:0b+lxBeJ4K/mo55jId/dbg==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:C8EvOcGqF/CiVHXeGqLPG6RCL4ffwx6PcSQWSk6najpXUlFrrS1H8A==,iv:iXqcz8wB+ltR1rSp+7dTRtdhxNVLieqEFNJdFPWmHP0=,tag:BCLNogMgVvcr8g0Rl6xVYw==,type:str]
    OPENAI_BASE_URL: ENC[AES256_GCM,data:auanar60A7liOxpheO57+oehIBajwxL1WHZbyZbcESOnepZJore5hlQcuACMVPkgfns8C4ixJ+N6nur1,iv:llBY/q61zrEGg/kqBlwjKmXpbzvDhfJI0Xnyf9cGcgo=,tag:0xDWZEJtuCNQNp4IUe6QRA==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Myt0OHB3ci8vUFAzYlA3
            aXo3RU01blNQenJGSDJQWUpLc3dLM1VmWFJrCkEvUTk0QmQ5ZllLenpmZHdYcHBw
            RTIwVTlWTjhuWkNOSkNHclB0SDVJNVUKLS0tIDlDMFBSV2FaQWtGUitkT2hLK1Mx
            RXMzMm9mK1BZWFFZSzZyMVZnVlhoeWsKY7M3XPxLEHU1HHbzxCUqVcvvBuShNWgm
            BHnCBL5ECN6JO6o7TCB0ainb23HtiPKub0EiSaqiEx5Z2A+WcKucSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T00:18:02Z"
    mac: ENC[AES256_GCM,data:nFxxM8DWJ5wvlwVUZuwutg7mv7TGkTN0D84zz6inoeYL0tG/srPdBzEbUDM+9XsRJHFYDMhxA8IyCDVgn+9JJYh3+OXPYlxeUmwQD270Rq5anBDo/XzAx/USKJA6pLCBW8tf5sWsZInFMzCesfOb6GZAnIPuC/dATmTGoLqiBBc=,iv:fsIz+qIJu8FGDvMXSoty1LBQMFQKQZ2ucHBrIa39T7w=,tag:g4rTjeJHWr8yly/P18Mp1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
