apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: transcribe

resources:
  - ../base/
  - transcribe-calltypes-secret.yaml
labels:
  - includeSelectors: true
    pairs:
      env: prod
      proj: transcribe
patches:
  - path: transcribe.yaml
  - path: transcribe-secret.yaml
