apiVersion: v1
data:
    OPENAI_API_KEY: ENC[AES256_GCM,data:9fp9vp/eOeC3ovoLDgVvi7fO/JkH5PS/uwNaGJhGHE2zinMsLE52Vw==,iv:MaQzMO4GxBQjs46drq3UldjSYeYK716MAwXVt/Lt9QU=,tag:0Mp39hhr6VrLxyCj4zOH2A==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:MfazHPHMaRwQ8eTGswaUeN8NV25xkFkKculMjlL1OxY=,iv:001h0RNrd9gl5TtK5/q6yMyuGCyMk+H7CkWI1GW+ON0=,tag:s7Q3KkoPVctARGrNEGX28Q==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:58n5nkmhnv8mGxxBPqvHSJ7ab4LBiNsIE1s42RycvRTVh1VWnn2gLZHcwRDr9RGr4/8F8D6r0TIuxfwO,iv:iLMU2lXrZuUzKViryQWA9scgE2Gx58mn+ghD8xUghQM=,tag:PznvRlLsIzIUNR3OeKk7dg==,type:str]
    #ENC[AES256_GCM,data:hNALRtLGez2U0vOF10okLnk=,iv:E5Jv5dazIau4RTQUp2PGTgh32CSSjfPs8MTJbnoibpw=,tag:rQfZr+Z8zyk9xmHHQkfyUg==,type:comment]
    SLACK_TOKEN: ENC[AES256_GCM,data:s+vTh9/ddDbj4SadFvr6oxS0Z5DJ+1z+mEYspJUlt4jwFx2Y2f/dC96bo68w2/g5Ka+Uw2l88TcKVuTeWFIqYhpCfryXswcwT0dnJw==,iv:7nFE/CQcYH5mOuzQ/tipb/bz5HBC3n0i1MK4LGJsH5M=,tag:tX6Gb+y8xZlFRo4X8xbhDA==,type:str]
    SLACK_CHANNEL_ID: ENC[AES256_GCM,data:4Pb6mfWUHabR9qY9ajNCYg==,iv:1zsS8Z48Cr2Ry2v6yjUbapLhwaXn2t5Jn3GPZ+Hx4Eg=,tag:wRAZFoTAC9gBPNOTFH/Gng==,type:str]
    SLACK_APP_TOKEN: ENC[AES256_GCM,data:++4aMI9lT8v2L2+U/RcuDkY6p215UklLTj23bChvQRITRz6DL8bZ8O4gK7SuxkvXe6SueFP0ODViSA0pNSDUV0UC1KUxx8wbpfH3wUFNdUk0mFxIdEuZg6WPTMl9yoyRvjnKPNMOtCPbPaeC7I7LXBguLVFZANME2KrrakzhuZ8RAJo+,iv:IP7AFY4i3prZqBTMaNqWhxC3Z7oD3j++Wwe2ANHkoCI=,tag:/iQtvRWBFCBArfhEe0FaOQ==,type:str]
    FEEDBACK_FORM_URL: ENC[AES256_GCM,data:Ft4RrnXJNW/TbPWhCS5+V+TBDE4/OvJo/Tb3za8X2vS2Z8oJDm6bg42KB6x7wJWaLEjcDZoKMlsHBFNnG9UVXVRdsKLhbRdAXOdM0IWWt/UIFDZLajvUeYZ14p2oOpc7r0Huq6rbLEgNS4l2RRjKmwd+bJHihtjSk8Z6bAxvJgQEjSln,iv:2dBy8jJjmCZox6UAhBENDF2/NbEqGDkkVS9IJsWN168=,tag:q84cfmCdIMVXkV3/Tonpaw==,type:str]
    FEEDBACK_FORM_FIELDS: ENC[AES256_GCM,data:mVNlNGenT23t3Dqe4V/OuE7AZd3KcGAy2qftZ81MgScuaIz18vFqVNyes1QyIA7RIuvOOgyQL8SckNh6TuFloNBzzf9n/nY6fw4KmP/3i5DVenfP4JuN4Qb/d27XaJCDENHw2a69wXCW29e99jQQ7QWqVKcwaEyMXXkkOFT8hGg2Cw0IrkAtOiXAUL79hmTCTxIytYap+8FXlWn22yBX+pMeXApGk0reBq8PVOntN9cV17rkm0F8St6uIho9qKB1gtXiE+DcN/QoyW/ESQ+N9mzJJCyV+T6tXgmQa++pGfSwpI5Hlvyn1o2KyUM=,iv:2MxUNM6IIpiGavcmPqdTe+7vVzX0+tXYpDnL0X9wRiQ=,tag:oJHO2Fb/2zU1wEAFYIe48g==,type:str]
    CALL_TYPES_KEY: ENC[AES256_GCM,data:vURSm3/QQdW0DEum2vYW5q1PqAKgKxEPifwrZNoyTt5OAsiAYB8wz2vdtK0aMb9No/c7dRFxpbL4Obhd4rAvfKn5HES5hbs2WXHBXIrcrBE18JEuFtldpQ==,iv:uG19PBwJvDxXdmEQ1yHPZfhEicOqgkcIEtvyWdQZpbM=,tag:7O7X2K3NYpzdY9wyCKFhoA==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:6OJYLc3uMYdwt91ZvqVXo3kJV+/0p/6QYAaMNKRke7FDLSevRbtFbr0Ks6YprWne9BDpF7nMkBY=,iv:WH1uXKq0+GAH5SRahcU6f0757ojB/LPb9p1obRCZSMY=,tag:/H/Vrp0/LSRBb6MFudJd+Q==,type:str]
    PULPO_API_KEY: ENC[AES256_GCM,data:ekUAMmPZdpVBIBEg95sq4rVkBqhwAGmUeh2qsM7vFsfeU9hpTU9b/AnwQXMk1BSAWka1qw==,iv:My6yQRQRVdmgrptbHN55Qc1Xay2W6HHAJTRjTmfPiVo=,tag:3NgJBSj2wAQj6VuSHaDD7w==,type:str]
    PULPO_USERNAME: ENC[AES256_GCM,data:u1OA4zHcUXLI6rWN,iv:oDhL5D7uhB6MnINgymWlQFqaTkgmFhMNGPMgQc8g+YE=,tag:CGD769O1Q0uPWJGigB/ENA==,type:str]
    PULPO_PASSWORD: ENC[AES256_GCM,data:wxQFjJ8XZj7cjKDBWXHpFw==,iv:u3ileLYKkaYIS0TqJR19pv4lO4hQ0URqb2eo+R8OVP4=,tag:FvaHjVQ7vsgF6Sgrdy4QTQ==,type:str]
kind: Secret
metadata:
    name: transcribe-secret
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Ti9PNTFUS1oreGR5QlN1
            ZTU0YmhjVklrUHV2Uml3OVN4OGRCQzZKR1E4CkgrTFYwekozVXA1YW5NUFFpa2Y4
            cVpPRDdmUTFyY01oeW92SHNtUXhIWm8KLS0tIEtGMzhVcXJJNzN2WVRucktVS2po
            b3NFdys0NlNaelRoSmsyVWY3WTAzV2cK8mPZekhD9qI8bJ+6iMgEGouZiQkUK4g5
            BwvIF6MrKy7RLVAoKYu7nYlUZ4m7eoW6pIH0FqFNJ6vWO4woOlbyZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T20:45:05Z"
    mac: ENC[AES256_GCM,data:S4uaD+M4WmFSIi0220vTLhnaTcvAX7s7JQ5s0XinZ7iE+FCQrpWGzynRyopW2+8t5rrjHQ1uo7Shfh0b/sYGVu+HGXrO5NLP8SxCGZ9pW/aWQQrP7LvKHuIWIwhDSQnJ1RJn5tTMJEAX5SnTMSPzNdAz3rFYdolTmO88e06X9nY=,iv:GN2k/r/Oiy1nO2iSG72MXfCFXEGLnhRKSj1PfeAMc4w=,tag:pacT8SoZsi4WUcEmuTpBmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
