apiVersion: v1
data:
    OPENAI_API_KEY: ENC[AES256_GCM,data:YbS/lhQ40V0btLhsf6dCzKJF2nZt7QHcaN4GBnFcYYFmLVt/gVOhzA==,iv:kZp4ALi9O1XbSQoMHPBwVU7VoiiVNPxR5b+gA9n5rVo=,tag:SICM99FMOIngJKQKQsmgcg==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:VoLK2arCXj3bFIZ1j8ixN5ngUltvvBkWP7Om/eZDiq0=,iv:R9GZmmjQCVHXUAOB34iZBPj62zT1ObaB9kk7GTMJOGc=,tag:7AuX0/GcJK9Y1THWet2RiQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:z4omu7oboLwxwRt4aaaRJAVMu/mHyAxeANz2ZMDFzL3S21pl0BbV6MDHpk/U6aVSbU1C2Hrugw1wIWD+,iv:BG79+v2ewuoWRWmfd/SYVVmAU6EnXkCtkwG5jxtjcbg=,tag:zJotGvwP0/CngONzdN8W/w==,type:str]
    #ENC[AES256_GCM,data:fAcJzylftQx7vl1oR8yjaK4=,iv:EXu3WRtMHopfHzUwdhtBOrG3EHQsMkHQOXGACTddEAs=,tag:dvsMlZYtmSqUBnhWKGW1fg==,type:comment]
    #ENC[AES256_GCM,data:JeScZOmjgMOj8tE5q8uMCuGneSr/UPF+wDhugy+UbNrJFxZpnVccYdB3VYx/3z2URXgxDt12PPw2AQG1g5abJVW4zL5SOCY=,iv:bLc/gyfoNn33NVNF6JR8DLRZg/g2Opln1PKER2n7piM=,tag:XkbMGUR5Qx+cQ4XkGD9f9Q==,type:comment]
    SLACK_CHANNEL_ID: ENC[AES256_GCM,data:u8r7T0bP3yEpCgab9pTGjQ==,iv:LflJCJJDnmmdUsnesR7ybbX1aJ8BR/hP0I/rw6U8xqg=,tag:er25J29nM/j1dMR0P3Bfqg==,type:str]
    SLACK_TOKEN: ENC[AES256_GCM,data:aCl6Vw+heB/gbQSjZUEBhutOj8IUa/bKtBl0P76tCBMvzoZozhegKpugVMz/jJEAL11MGnR7nPuZM7jbMHoBYcSJHT1qgrR/XYkCAyNcRzk=,iv:Mw3lVNVhsX4ZAhn6q4P+V3t2HFHYwfdt9xCaZemWquQ=,tag:WzZ3ayDLMbIosV2Y1QnTXQ==,type:str]
    SLACK_APP_TOKEN: ENC[AES256_GCM,data:gTddcgPD9zUBhZMykCNhmCrV1tttsC/qSEzVSnQh6dfEy9ovHQ97X9GGe2+jf2407eEvNu1IXe1vt5McOAeGZk1m/6TNuxv4xr+qS03gJsG70MIitCKvDwsBhFclUmVnEaTrXLeS/TsK0deZi2ufQxscBB5zojCnS8HjyUa7z47VC/wR,iv:nK6hk6KuZdbt2ntfBGg990d+7Cb3g9DUKy7iS2cnfao=,tag:29kWzeIrMY/sNMsmUMFJKw==,type:str]
    FEEDBACK_FORM_URL: ENC[AES256_GCM,data:I4NPH3jkshgIVBybChqVO5y/rlRUOZfmkGFP7Ck+E76MH/5nEAHeaBSIR5B2EbM3k97g9BXi+OeU6MSub9iglWLF3HppyRHLB3RcLWRz944LVRmgV0I+J9DjXsELAfQdI4utZf7B8hDjUZF+QV4NDMDADtXMEW6Yt5XnxjzJIhKb3Hls,iv:IzPp6RTJa9gtctxBbtkJ39N8K2pS6lqaSRLyfXE+ZCM=,tag:uXH7oJRGwIMKOhZ+wPH4PQ==,type:str]
    FEEDBACK_FORM_FIELDS: ENC[AES256_GCM,data:g4DVSD/XZpvs435O/stBKGeJq5ANhCRQQOTR2obQt/z8rAnuTabtC1ZEGgLd3C/2eA7vf5vW19eA+UbI53m3ecWuupqBuG48Z7KFNNT8Nm2NDj0XZJSPQCuAyfp5UyjSe19PQU3LhSXNOG9ORBY/U3KAqbxtQslh9WEROjIclPSBXcawB6pAoCQ2FthT9R/haBIJ7i/og/uIjoErWjIqZc7jG7O3cbh0wtFI2v51MUaM82BxwYk0CnNJ30iHqL9fuIq1wYdTqXUl8dg7B+NZQZx0wo4fTA3nZHFzpOPprE+ZfbQY7YTTNI1pylg=,iv:ASLzXyjuTx5SQp5UkdyPDGcNS5XJgUOBujtRceeuWiw=,tag:ZkgnHAnY9FLMrzyeuRXysQ==,type:str]
    CALL_TYPES_KEY: ENC[AES256_GCM,data:xiWEpjPFzL/InTVIuV2wcQ++gdyhyJzHFcoib2faXwBuMvse0Ed5+cIEhWDqxrbAEdmg5jhM89iLwq0tvUb9WzCWov9RgDW4i1Erm+hBkvpZhgPRD68ndg==,iv:Hk1Muj7hHeytI4EFIqvRLh4cFUsiRzn0JWNAzC8Vx2E=,tag:3oHHfTzH9lAUt92vZigT4w==,type:str]
kind: Secret
metadata:
    name: transcribe-secret
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWlR0WGhyVExIbUIvcGxX
            YisvV2FNejVybitMNlJVRERKdXZlQlRIS2g4CkZacG5IT2xLV2kyZndjWEt0b2xh
            SWZ3NkhmMktxMGxDb2lmbXJYUSt3NW8KLS0tIHl6NW5RNVRqSGZhcXl6QkFEdURH
            MWU0SGRTcS9wYXNsWDRhMWtOc3h1SkEKyC4R6v/pBV7ChPFZUIrhbXS83heI8h+Z
            b1G2sdA+znnZovWwIeMEAfXhz/Xby+ARuOfTpmHxSTnfoPiG/xy3WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T04:46:05Z"
    mac: ENC[AES256_GCM,data:9iYXsmotZl6iXYLjBnNplz5y5SQdG02nhMgtQMMBZa29Uc3HQ8W2ljhoDB+nBgD13q6vq87/eklUiibOlZbFNpmwLn8wIupEG+8TyPMRNM5wR0dsmim4ywJ76OzkJfHSdOG97Q62Xfxh/1RszkFmEvf7xszfBK57zQqv/1dJPj4=,iv:q8Fidh5xtR6wftJLvWcfxm0MPN0AD/Da25Qv3bcwVsU=,tag:Se8CejThI5YNj6HJyxa1tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
