apiVersion: v1
kind: Secret
metadata:
    name: grafana-alerting-secrets
    namespace: grafana
type: Opaque
stringData:
    GRAFANA_PNP_TOKEN: ENC[AES256_GCM,data:R87eKSKutP3B8qmzofqzFJZu8cTcyqMx2gHqHyCWfxRMhFME88X5kDA+1+eSKbCv,iv:YHm4sUAlZwZcK7d/o42+92M9K5QtnQuQ1fg1XhpNQZs=,tag:ReZdNboREP0jMDsfXqZYzw==,type:str]
    GRAFANA_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:y1cMbyfbjF9UAE8dhDnMZSL/mOEYTp9PFVjbXth2,iv:hay2fmm1o3Vpx3GdctOwV36d5xgOBv1fhmbVzMTMmds=,tag:i+72ZRjUmafoX8mqCmTVdA==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQ2tOLzdDcFZDVW1jbHhR
            VHdjNUlqY0ZrMXU4S3Y0QTEvQVhHVzQvWXcwClc4eFI5TU5rSmFWUzkwRGdmVkhX
            biswTHpGMnhIM2NnQzZtRHNYUjQrUTAKLS0tIHJhSFR1WjM2OSsxWmtuaklWOUsr
            OVZ1cUJKUjNYVzBvamlHekNyanFBeFkKuBoIZ8LKJPMDNjeK3tU6Ei0Pu7CBRrqF
            xUqcEi9b6InzZQSXPX89DFI/mNKyRmjcEVLu3PBgjPHxpiqZTEDZ7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T01:11:09Z"
    mac: ENC[AES256_GCM,data:BTKXqXARxyYqLO6GSrTXeZ8xegMdT/WbP1uGryQDHD/PYGDGsfDOcTU6YL8xAwLt1E8QZjO6skE+xUkSGM2KWmRMxXCIyFIC4QZIrcgpEQNLgPap1ygIDEO9veUmgTWdcgIwfgtMpjhqxjAlKMljOgwrM9ucwfbxG2kNHzbxDVI=,iv:Qg+dOcgCatDZadb6XvCCL84zFQJAmUoE3B5JGDg42tU=,tag:sO8tC8o508uysIr6o0D9LA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
