---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: lgtm-distributed
  namespace: grafana
spec:
  chart:
    spec:
      chart: lgtm-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 2.1.0
  valuesFrom:
    - kind: ConfigMap
      name: lgtm-distributed-values
  interval: 1m0s
