---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nws-forecast-summarizer-scaledobject
spec:
  scaleTargetRef:
    name: nws-forecast-summarizer
  minReplicaCount: 2
  maxReplicaCount: 4
  triggers:
    - type: cpu
      metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
      metadata:
        value: "50"
        containerName: "nws-forecast-summarizer"
