---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name ollama
  labels:
    app: *name
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
      annotations:
        prometheus.io/scrape: "false"
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.istio.io/merge-metrics: "false"
    spec:
      runtimeClassName: nvidia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: k8s.lfp.rocks/gpu
                    operator: In
                    values:
                      - enabled
      containers:
        - name: *name
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 11434
            - name: metrics
              containerPort: 8081
          resources:
            limits:
              memory: "3Gi"
            requests:
              cpu: "100m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ollama-httproute
