---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: lfpweather-api-scaledobject
spec:
  scaleTargetRef:
    name: lfpweather-api
  minReplicaCount: 2
  maxReplicaCount: 4
  triggers:
    - type: cpu
      metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
      metadata:
        value: "50"
        containerName: "lfpweather-api"
