apiVersion: v1
kind: Secret
metadata:
    name: lfpweather-api-env-secret
data:
    TIMESCALE_CONN_STRING: ENC[AES256_GCM,data:huPJRBb3xunL0T+YvXsG7qCgKOpIR2xceqPJ2+Md7B20WviT9dxnHfC0w8et8lYWoVRi4Xn19Y5A6mA2g3nJaE0U1LQnkqNEcLTf+4widi1amVoyiWJdQ6m4pD9/Xv+k,iv:jqrGtfjgFI2mDAVDeSUBygwLHupc0n/i80/jTjyw1n4=,tag:dW4ZHKIv/mHAat/O9fIxMQ==,type:str]
    API_KEYS: ENC[AES256_GCM,data:qmwy6W2f3jhDdu/vrzVAwgR/yXJFAGUWTkFtEWdqrlun9XVFfxJSAPIgB08=,iv:+T9Sa+T/IHhCA4eQJvZPh7qZdE2anbSun2C/kE9uXl0=,tag:43UAbZJXCJUrIzpA1oJRBg==,type:str]
    ELECTRICITYMAPS_API_KEY: ENC[AES256_GCM,data:gwC87ql4NL0CUPD3gzkMMj/mytMHzMs9uXTLyg==,iv:0tB5O73hspO+Cne5+nOHX3OBAFlUu4sfoSy5lWSoAmI=,tag:Hur1+C2WCUim+SNLWwQWzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxY28rVzRhQVJHa3I4MkFB
              RFp4SjZrc3NlWE45QUZlL1pqZlAyTFAwL1VZClpVTFVRR2hDcGpOMVIyRy8xNGlO
              R09mb2t4b2RyYlFoOFQ2UFNaNE1rcVEKLS0tIGJOMUViS0J4ZkNxZnFGb0szT1pF
              NUd4Wk1uNDM1WUhZeXVnbHJFZjFkc0UKdZwu/qNKLGiO4mMaDI3Odu9TLihHIlch
              FgTAAaNJnzylw3PmZUDNc+E6u6+zacfMK+DfJeUFEmsYd7fEcJUcRw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-02T16:25:33Z"
    mac: ENC[AES256_GCM,data:KoIoY5GaJV4O8nL+MJA1m66XQAdDzxMEkADvKqfL0wY3oNFKZsczwaltu4BNrkJGk6zWMiN+onqQeyaSQ/lgktSHYsS1XxX5xcnp4JipjeimNO33gsxyLIlEqiLbFqK7ULZLDr4Nzf7cOC37Bqj6UOwkJXbEvw06yz8KUl8LdXI=,iv:/8YSIVXx7/cEwjz1JUt6FFenMBr1TwChbUALYrcoNcU=,tag:XOGRUO7/mdTt2UnA5V+L0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
