apiVersion: v1
kind: Secret
metadata:
    name: llama-cpp-api-keys
data:
    api-keys: ENC[AES256_GCM,data:udHDHHwCopK2zB8FnTq/Z+1j8n9+2HxZi8/DmlF/pJAO5fxkCR5L3wKGPPM=,iv:yWCGpCZyHzj69Qjmke26p6EiQks8cq0dKHEjyGkt8kw=,tag:Sg5xWu1YFNszuYst3RbQ0A==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VTV5YVhKZGhqZzVaNjlH
            UVZpeEc1d0NBcUFXek5yYWhuYWVCcHUzYjAwCmdISHM2SzBuVm9IU2lyajZxVVlr
            UDFsTWVETWl6alhLbXY2QkZpSDNjdGcKLS0tIG9OVUFFcnpNQ0p5MmZ0RlhaV3FG
            YTl1enBjTC83ZXhRWCtZSXNUQXR6Zm8KXf7qmOOlZw4G4/KuRG+gu6O4wnIL/3h1
            LZBBRaox8RNWYtqMuWXCPN0gUiYiJ/lJaoWxVcXo4HvCBLJIwvqmBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T04:58:18Z"
    mac: ENC[AES256_GCM,data:nX5eQcLJ3lg3Fxk/FmobBpU+SvWtk2mqwVxIBDPhsAB0wTwaUJDBGLCjAmoZILdJ2bV/17eS0n1K1mlubcmUvVCzEen1I4V9augTptBFNsM5n/0d1DzR2pUx8TjCc97b+eZcR+H7PPx5yTL825ORhrlSQFD7tnFIrxyIjczXUso=,iv:ai57Hx9M40J4sez0gZw4qufHF0udcvcCBbVhAFE7ifo=,tag:riT2ebFzgeBuLVeoigPW3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
