---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lfpweather-bluesky-bot-env-configmap
data:
  # logging
  LOG_LEVEL: "debug"

  # metrics
  METRICS_ENABLED: "true"
  METRICS_PORT: "8081"

  DAILY_FORECAST_CRON_SCHEDULE: "0 6 * * *"

  # yamllint disable-line rule:line-length
  LFP_WEATHER_FORECAST_INFERENCE_API_URL: "https://${SUB_COMBAT_PILGRIM}.${DOMAIN_COMMON_STAR}"
  # LFP_WEATHER_FORECAST_INFERENCE_API_KEY: xxx
  LFP_WEATHER_FORECAST_INFERENCE_API_TIMEOUT: "10s"

  # BLUESKY_HOST: "https://bsky.social"
  # BLUESKY_USERNAME: xxx
  # BLUESKY_PASSWORD: xxx

  # tz required for cron to fire at the correct time
  TZ: "America/Los_Angeles"

  # tracing
  TRACING_ENABLED: "false"
  TRACING_SAMPLERATE: "1.0"
  TRACING_SERVICE: "lfpweather-bluesky-bot"
  TRACING_VERSION: "0.0.1"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://lgtm:4317"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name lfpweather-bluesky-bot
  labels:
    app: *name
spec:
  selector:
    matchLabels:
      app: *name
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        k8s.lfp.rocks/service: "lfpweather-bluesky-bot"
        k8s.lfp.rocks/version: "v1.0.3"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: k8s.lfp.rocks/gpu
                    operator: NotIn
                    values:
                      - enabled
      containers:
        - name: *name
          image: ghcr.io/michaelpeterswa/lfpweather-bluesky-bot:v1.0.3
