apiVersion: v1
kind: Secret
metadata:
    name: lfpweather-bluesky-bot-env-secret
data:
    LFP_WEATHER_FORECAST_INFERENCE_API_API_KEY: ENC[AES256_GCM,data:kK+++3p2kqqdiCHQpuz6Nne+vHF1GnSX9vIK3D8AEG2qM6cqDlRU9YKwhyE=,iv:ktZ2yGSO99RY5hXNI0BbT0O1h4igrTz8TBUaxpoNkyw=,tag:2XXkVbiWqpEPrHdkoRLjCw==,type:str]
    BLUESKY_USERNAME: ENC[AES256_GCM,data:p6X/NLXz3wXKl9yT+nCbII19VjYJPJEKZbqvBDy65FY=,iv:Fu3/10V93lWeiI1r8wfnN50auNMQqP3HKPdMF6moZt8=,tag:1l/qRFLOdbIvmtn/DazXPA==,type:str]
    BLUESKY_PASSWORD: ENC[AES256_GCM,data:a1f3oSevkW0RX8v6+6udIfDuStsREsrA+gDALg==,iv:3GWbT0eN5iiKGh/+poghmk3ROzgq6riEns6LDpk1a/0=,tag:NUPOpuGVUEk4ScnjRVTJfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTWdocWFlSFpaQlhMWE1v
              SU5sbUlVelpjbG5nY253d1grMGFDblkzb2pNCjUzM1FKeENkdkI4dkRQN21PZnd6
              eTRnMmdzRGpXdEF5WW45S2ptWW9KUUUKLS0tIFJyWDJzZ2hydnhHbit5c1drSjh3
              UFVSelNmS2pSTGlUWWFWMDNjKzJKcWcKNPRXBQV3zQaAssZs3HabwwHhfpBpRyhE
              mF/XnS3mgZ70pdJLGVxGPfeCGmvGhAvBvs1yzFi6fa4hm/BjB0DDaw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-05T04:45:56Z"
    mac: ENC[AES256_GCM,data:9Kd0rU7arMpfnVsyHpz1RRNUfiNm7WGknEsXd4UHvDPZGbuNs91vHLLYvuR5KfAE+GGxhnZ530Rma4ep/P7hReXJTQKHz9mRkrmDNz/1TDLXmbX+0/42SliUyQ3ePPoXczFC3n9e9VdoBjrnOce95bXRYlzASy27kNksx/bducI=,iv:ybA4PJc2xYPYjTU8K3n7j9A5MPVvqZn09y5j6BSuZ1I=,tag:ENkRgNDg6LfxCzfly2eGhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
