apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:WFjr3sALbMW0A1Oz0LWAc4/nuEMUFXhpNvLvLP+TWwsMUPj92+RD4WEqmt+rkMrj9PNHII7O0y3bLp0FoHHxS1NkOX1uZhQQj3AjExXE/XeILhU42p1bfj/sonbN9jt44W/psDsDODdqWNXGTQREq8vSbZci6X614mt9tXJHZMxrzeNg5iLJRuzuQbYgBCUTY3FfnLiVmm/YU1Qsr1WpkheMYOdNKpufmvVwSvaU45RXi76fXy2h7y4cvV00Wm8SHjl1jRkJaotVKC/LK5i3y5nT3CgR70RPzJ2Dy/f8Kqh6O7gHWGkolg2sX7InLxN69xL8c7asyNOX+Sn9FFKW9w==,iv:492Nrry/ohqwvEqsAxMyrJk9936B2hnBmjS5bNjJFJs=,tag:3T1pLqvAeLXedW7BnekG5Q==,type:str]
kind: Secret
metadata:
    name: ghcr-alpineworks
    namespace: alpineworks
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRHhEb1hhNFovcjJQcUR1
            Wm1xOEplU09iSjZCRFRzMDZGa2haYWVvNkdJClJPY3kzMXVwUGlxaHJ2d2VYZUtv
            WGFCMzBQRXhsa3pJSnU2SGl3TVV6b3MKLS0tIGZTMThFK0NZK013aWFUeEtxRWdE
            bmtHQ04xT09IRGJaNGJ6R0hUblJqa2MKKODLu8FNzCbMCdduBLs9H44mo5BG+3+U
            cwP1BmwupPQ0LDED2lznj6Cvwi1x9Q0KtKARkDSA2JsSUwm6gnS/MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-06T21:02:49Z"
    mac: ENC[AES256_GCM,data:yQQ++tU1m93Ye4lslk17pC/EsGyFcYvkGQuypNgD/ZQ9A+Wm3g7OKGE7iKXKF2V3RLc2bfNzuqg1yVyVBpuSyxt9fSf1AToATeT+CbnsvPPXCI7gxhURKZxAZ53Q6RVrbyxd9NzX+Til1QigXd9ag/6DzjzDf84vikc7H9XAZ94=,iv:a3kZGrKfVy+5mncJZ9m3Jd8DFZ+00hLWeNl8Rle2Ito=,tag:vDgW9PsMO/Pzh0hpY5M+CQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
