apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:qlxgcm8s5z3WpVFfimQKOAgWTCDNLZDLw6kcxk4STqE9dftonfjRpHPqSQR25wQW07Kn3ZMfuJAQuvvprywShlw+HtcQKmxTT5ElmhhHHas1GaYF4Xheya8OnNw5fNb0,iv:aQU1lJYfUFBaB5G6cGXJw58qGRPgK4f8EgKS6Q8rY6A=,tag:ngFhT6xOkH5wOlM7F800og==,type:str]
kind: Secret
metadata:
    name: buoy-server-env-secret
    namespace: alpineworks
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWnk0NDZLckYrMkZMZDZ4
            N1VCSTNmdUh2dDJSRVg3SS90L0t2TVhFQ0hvCnViOUp1M0NJY1ZleUpDdFZneWda
            VzRsbzc4ODhBZzEwcDBhQ3huNjFGaGsKLS0tIGZSVm1rNWY0VjZMUEtOcnVxWEZw
            T0VWN1E1ekk0K2tmY2FVZEI2dU43MEEKfQHdgKEOiwzcQQ2isQiS4+1uEfGIjpWJ
            owMNqEfTTgsceytM7my69qUFml7vStd5tj/vjiUjU5RI1pQeojTrow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T01:40:55Z"
    mac: ENC[AES256_GCM,data:laxX5bdVny+bWvIBR/synZVtvUmE6lEWxdrGPgqSlDDDW010GXKa9HY1eU8QHF18ii5Q5VHChjmR257PqF1eFaY0o9llx0N+wKgZSn/OUHE0hyHLg2yO/O4waDdYflb0FXJyTQp9DecfGKtXPMRSsKk3dKs03LFy2Ga7dFCH9cI=,iv:kxNfTKght3CO693ylZfYveYJ1fUxoPKrALf82LzpZYw=,tag:kpVNzNid6o/Pw8EzlRWIUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
