apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:KSuvkBXKm98kltG0sfx8vLnFjkuioa6tC3fAr9plYXtpwJHN3PiKeWqTfsw=,iv:vMgETnizZ9atSvNJNzFfdKoGI0iR//QdNOA1uovF/jY=,tag:Y8aan95rwuBEttDnCVxJvQ==,type:str]
kind: Secret
metadata:
    name: buoy-server-env-secret
    namespace: alpineworks
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtU0U0Uk9haEh5Y0hEa1o3
            cHl1eFVJbVRNYzhpL0UrRHFyVnBMaFpRc2dNCkJaWFNtdlhkbWU2c08zSWxzcFpu
            QWdRb3lZa1Q4V2ZJQjVCMWxURWlIUzQKLS0tIEd3RmVzOG1qQ3ZvZHhBVklzNTM3
            Q0gwd3V3bFY3dUtJYnBpaWtsdlhHQmsKh0rXalGR5wMfBZH1had0Zl2bXcOKY4DQ
            ydFx5PJ1UOSsGvH/i5T0FTrOPpodrA6nF22lZXivTXkH7pF8eGxflA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T00:55:40Z"
    mac: ENC[AES256_GCM,data:TW90eF3QNLFvAfJTFz+aesvMIGb/byDj/DpevyjCtAc/9Q7hhOGk9J5zJfqJncVl344qOVzinVezJ4XMRSVbR5IEIuGgnGqmjMvmORrxmCfyx0JQKJG+Tp2qtTQ6XgSKCIxhO//e/NWQq/SM+D6+Pt2CjWD2GHkwtigtpG/pI8A=,iv:q33yKfeiGk7pc/dipiJJgI+6Oi6j4PeXyhZwRUcIyL8=,tag:ty7gAO0NPejKcoyiPCuViQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
