---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  chart:
    spec:
      chart: paperless-ngx
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: paperless-ngx
      version: 0.22.0
  valuesFrom:
    - kind: ConfigMap
      name: paperless-ngx-values
    - kind: Secret
      name: paperless-ngx-values-secret
  interval: 1m0s
