apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-values-secret
    namespace: paperless-ngx
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:q3n7fUAaNyEYUcsBGQgM8iMi6Wy74aYpKnbfZpTkm46gOlHu+CCFcK3fxa3UTkY4jL7Fcjq3ESLTcZXPES7Ix7TDCvLun8Mk0RzvMpXMFmhQbjlm3UYtMKT4sGL2bsKLPvRtnKEsEphwexomB/2EntDl1WXrwOGVaVdQb+rp2tDIFSn7TLRP+7CiRj+poUaVaz1nkcsRGT99,iv:1WJjlOiqmpPjNUHFVAulhwWDEQkO3AOCePy9ib9iEjE=,tag:FsFuO3O1arZuOdU1j6ukLQ==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NHJ4bkcvVlU3bDU4cFVM
            dlhEMmFNdWRqbDNTL2FkWlpYM25pQ3RnTjJnCms5YmlXbkdiS0NmT0JzNU16SkJw
            dEVyNjhsaTZNSUxsenYwUHZmWDJNZlUKLS0tIEpoS0F2MzdJeHQ4b3FONXV3dko3
            N1VCV2pXSzQ1N2pUclhQVzIrZVRxa0EK/V6kpq45/bIZeRA1HPEnUuaSJApsn6sQ
            VuHDVlD858RWgCPmVBr4iRVWsqj13P5XDr7KTEFyj8sQ6kj6ZQI/xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T19:44:00Z"
    mac: ENC[AES256_GCM,data:zli8n1DhBCS0ROM71MteLlGv+0axnzbVCip4JiCPOQ7HhKnoT0Hb4Nd/6l/1NbtC+87RjUgJl8FX0pDOjWukzHpb5E6seFNN0wgLL/Cx8QTX9O1ZQPv4uEg8DibgYJuwRUQ+J3Ndy7NRaXYvP44qOJxhc5YNP+NmGHhcpV/3lN4=,iv:atBTf1Qw5FHhRM5UZUiETmemnWcJH/r22Gy59sSGq5Y=,tag:xddpUVQ7E+o1zFayHzH10w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
