# Sensitive Helm values for paperless-ngx, merged into the HelmRelease via valuesFrom
# (after the public paperless-ngx-values ConfigMap, so these override). Encrypted with SOPS.
apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-values-secret
    namespace: paperless-ngx
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:+L2F+gXWhQpvQVGhMFoWCdVRRbS8I1ZTlZxNWr+McTPRPv0gAuF7hjzIWll9xXn8sUDX9ncqg+Pxtq3D8w==,iv:YlDLUbN/ykRPrckGTyFUp9U6eaT838wtbiG8lc/eKv8=,tag:xFkrKGpDlxE0uu27gKV3rA==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSm1VeXZNaWIrRDdkaVVn
            NklYUkNzNmo2cFVqMk1YTU9MMEhlWkdNaVE4Cm9VdDJmTE9OQ2hoNGpXSk1wWDg1
            cTgxUFNFbU5VK05La3VBRjh1RlQ3eEkKLS0tIDAxVC96YzRlaEFJaVIvNTRURzEy
            NHJWSUJVNXZZS05Ma1R1TzM2NFFGWFkKhZ66D8aYKRZB0lQekU9LEt+sq2c+lj30
            TOb5dtQLBPUYZ+ggsNLSm8YVTVHVSGewMFX731dQACLWPY3PdvVc6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T07:20:44Z"
    mac: ENC[AES256_GCM,data:ZT29OzpxRW5caWI0mhoPc/cKFN7wBX8qDrKbi/ojIYILidZ8UdkapaJkiHJapgbCp/VLua5DDFMkFoXMYkYUELVUDiDBRcnxo62QOJyOf/OhPvll0xy/MvUGUfO/alBcJZeaBemzrtIDlfVRp8Wa43RbNsLnl+2f2hy4hFz4mGc=,iv:L2XGA3cK6PUoSiwTk+INp9nZ3E0S4gbf2l2g19t9+R4=,tag:aDP+DDazEvctUZgUwq+bLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
