apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: versity
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: versitygw-webhook-pulsar-proxy-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
