apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw
resources:
  - openclaw-secret.yaml
  - configmap.yaml
  - sandboxtemplate.yaml
  - sandboxwarmpool.yaml
  - sandboxclaim.yaml
  - service.yaml
