apiVersion: v1
kind: Secret
metadata:
    name: openclaw-provider-keys
    labels:
        app: openclaw
type: Opaque
data:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:Yx8hOjlWzbs4SXHBNGNpyDk6blGJnhriwDJ7FS2FMn0OTqIiPnPTj1wS9cP1SXglYYs2umxHGcPzlNFqr3vPY62A9ovLeyfU527nHwYRpRQOFct7MPb4CA==,iv:W31AQn8GiAaRFINSIghePIbm3Q88gNyF4NH8nfMBx/Q=,tag:WFAxIt2NFV6W5Af4J+xPLg==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:c4bIJsgbKYxMINgacG9wzkb9qTZv/bzxrXsxFYX5UpwXuCEyU2HuAYvDviKQCezf4U+vpEAKUw3TdXy4X38mhwvqsh1cvKiNAAj9KBAHiBaSpob33xQ7lRpAqYCztMVOyKeTIBVfPX0SC1Z6yQY7lwkaImXMO4n1gp1SLIr/X84rOH/sp1kS4nE6bS7Absld,iv:uX5I3MUvbHzfciu9Q+xW0TxBWkuV6UjkjZanyCuPtfw=,tag:ifxj4DtH2B44uy096Dt7zQ==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSTZrY3Q2YW0zL3pjR0J0
            OVBCckxHWlVacHY5QkdaVlRqSWk0THkwTTFzCmU0cDYvMWc0Qzc5alQ2Z1p2a2E3
            bFZWM1ZMdUc0RFIwcmNTSURNa0NuNzQKLS0tIFJWbUl4TVRSdEhTSWdlZzBYK0JH
            Ni81Y295RFp1NGJhdTF1VENvTHYyaFEKSZmacR/okT1LB/gW9fUKFxno+kaphaA8
            9ypbSykBwR2aemgLiHc1PSleZLmMVajESkvwXB1JrPMcU0ugwzgv+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T06:06:24Z"
    mac: ENC[AES256_GCM,data:Kd9qe0Vci/y8HXXJD7m/3YMzFqQauxMxcj7V7nOU1XmAsbPjKUUSX3fmLiBlE2OmOjd+8bieAeELMLSU4IdAjhhKjpenVLWk96xj/MyJbG+D7E44UcS9On9B9MRESRPRhJUUompd93c01k4TK3S726gUoZu1+MmCt4kbj6btL0s=,iv:xYiqPH3meuibwJZT3WdUUH2+fHAaX7cT6VY4R/BJjX4=,tag:H0IeK1X+rQSHP+xVcbMvxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
