apiVersion: v1
kind: Secret
metadata:
  name: openclaw-provider-keys
  labels:
    app: openclaw
type: Opaque
stringData:
  #ENC[AES256_GCM,data:xv9HMKn5jNWIQD96zEMdp2HVmvylMpbe3TbLrw0zqL8rolw7rYZsYE8TyyjgDsEWVsVtfCHKc1oFkKJQGpwGXWBAfKvGR+G6QAe+,iv:TWtD1Tt1sDf2Um+HQxEdFzdB01MxQloaNazrpQ2gcLM=,tag:gti1Z5KZXJWhiP8+QFbi2g==,type:comment]
  OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:PgGqDX77W1C/A+M/Cpo+1wKxZ8Q0xN+iuOeYjkud8Z8OwxncmAZMwtLHRm3qb7rGNhe7WzZsS6I9+r8oMdOi/A==,iv:PUDpoglBH49gDd1D3poKKfCnCdv4ORKtiRSubs4zVtk=,tag:Jg3w52QVEGpc3+ehvWEUEw==,type:str]
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:Cw7gdh+mUsRtfd1PUILTCCY0Q+3mP/JIG1mxxXFgbIxMzlkYc6QqlBvDL2OiCmCY4lDANjtsYXfVmhqYYcJ/hGUTc1TS2CRoWLBuGPg7nVox3aX+2942pL/2xWc+GT6yyHWAexUA4FrvU7oa,iv:Ob4fVauFi0Iri2vIdJyletxtHYMkreZjm1F35tb4OPI=,tag:hMWQl/SWPd0hyaXfO6bCUA==,type:str]
data: []
sops:
  age:
    - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRyszU3gveFpmOGErSkdT
        cHlDbGZybnlSOXB3REZUUTFmcDNuTmFGTFFNCnBxdFhhS2dGVkxZMWhvVlJ4U3NB
        UTFERm84ckQyUGptZUx6MFE2KzdrcncKLS0tIHFOR3ZVanNvclFPMFNJcGhORFU3
        ZG1pKzhEclFhWTY1R0lHVEF4bDNQQ0UKWCNmDubXwxc4EWV4L6aUa39CllkGUNW0
        ObxwFJLVJ7auuo4z4Lu1KMFly4AUgkBR4LIR/IPxahmjghuaENHAMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-23T05:59:38Z"
  mac: ENC[AES256_GCM,data:y4/PvSb8tNhBFNudtevO4525JkR9lDYm5IsoDw5VHlsqF9eCZboTX5cJ5IDfZHu29jxDnZAYZssKtXM0gLeWERSVyYolHKNZTnoCp4AG5XitJqw1utd3/lFntIF/Vf2r5Yvh3aiuWi9dxItZAmft3AIvDe4D2qwUKlpOSI7OITk=,iv:iw59VoI6aTDYoONY634LSK9qZJP8Z/4OI+F69odIXaU=,tag:bA0X67e+IGSQgykfrrynCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
