apiVersion: v1
kind: Secret
metadata:
    name: openclaw-provider-keys
    labels:
        app: openclaw
type: Opaque
data:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:GuEfJhlX+mI3rDrXprC5GtTCi6q2ozqXwfu7mv6aLXwV1W4K6KMs1Ice/PZ6SZxzG1/srAVZyaUVixjxTIYyJXTKTekqoGPdygdyy/ia3jOrmQkifgK4Aw==,iv:koRR4TOWWym8CUpPo/SF3TpILM9ftp56jpT7ilLQ7KI=,tag:TlvhoMFqrc40KYK2chcs6w==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:3xC5shXZ3uWLhJsEMFczV/ltUvNz5m/uEex95cPtrRa8D0YUwn/Zg7/x+uyWyhvmOZ6budjYE1vMd5hDRGutC1HUyJX0zWeoWCJuJqKRRbMqr4uXp6nXsJs84qeaOJU93WuAd+3YqHXEFJspCCtNhCU09FbgIsqWzjrViWV+3ggpw2tWYPsRprRXGYNaPCEY,iv:mPFH0B2uu0uAlEauNa+OlhZUcQv0YuI3fxJiqQIAE2s=,tag:4mQsL4d7LR0pdzEy+wRiJw==,type:str]
    WSDOT_MCP_TOKEN: ENC[AES256_GCM,data:3mil05GmnMreDIAOglNtyOHnLT6jB6niNBJ5akcTlUFj6zywy234J1d8OfptFOTXEI2kpGqHy6UVZAjXoAZCKVcVHeubj+jkzJGWeQWNI3DX6y3LlgaUdg==,iv:Ub3HPXj9b3hekgAxqJapO50TtMxFZj0KqNPPVO8N4Gk=,tag:EGxr6xyzKiySvhshzJ54Fg==,type:str]
    HA_MCP_TOKEN: ENC[AES256_GCM,data:cehShRZ5i2c9dVSqBtE5Bfxn4ACW9XTSWCjd2l5Wr8wosbvw/HzWlnrqQquB1ANAnWDv9lC3iv8A7nQ1yf0Wcp6gZoN/dbmd5QC3AXMj0Gt93rZwIq89YkPZtZJfbU7J0bPNjD8N7vfcun7OQCDnOTnBRceM65tED5qdI2wGDwWkNXuanxs87ebccE9Ye4sH45LF891PItlpcINtdoritAtSAfy3vYZ/QkoFx9ehlWexZiepB1CSnWWJG1RFYE860EclkmyFgOADDg4/BOlg3HtVruc9sGgqE9R99lL0lXk+6IRS77SB2YUSgKc/Q1+aM/zq6A==,iv:1cZhR0dokxXTBOK1rxzamcNs3YDewtzW/nK745KYZZc=,tag:vQPmskoEbZtRIvrylQnbsg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:IBS2PEQY//HMM/MEEG5nfGmy190ff45SaUlDFw8vMQr4SIrc4oQIitbCx1MK8vl/6KvAVO/TQe6MkcWR/OSdUElyxW0RrWZieV45hxsYw4aaZs/ZVn1j6GGn03cGn0kCjP/W79GRGs5pTJiXYxlxqpGlUfNYWUXOeoxbcA4zMnEi3/ZcJ/fbMd/V+obZlnz8g59B0ME4K1UG9qOc22KAqrxFXWn7qhW63IYZ04Tu5387U3xsV0ecTLPPLwPal3N/mUXnxM5yP9wwBkAdVJo/c7Y9r+UInpsM9MFLtg==,iv:2vWrrpU4Q5foQ+W76XfqjA0z/Jzs0D76enfUp0vuyKE=,tag:iUMdNgZqqK9/p+CN7PoF8A==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:baOA6CcjPpjTKwQnF7zUHAJ4LvVB5gPfgQwJXYZNIgprIxwudBiR8P2AY/4IA+To34OU8fvRJmhbO7PM8vAUJQ==,iv:NjSU0DMPmpmaun5DhBw3ctxukdNMZ4CheSRySohZ+5w=,tag:m8Whtb5D0NF3SzNIrFjQGg==,type:str]
    LFP_MCP_TOKEN: ENC[AES256_GCM,data:5n8RpNZVXfD3df8fO6Ap7dpJuYsWRlap5ZQeuoghW/Ei1ygWvk5W9i200jk=,iv:741kcLkJt5QmUWrALAzB4Y5jQohd3CII37i8qpcTeOc=,tag:mXfz3yI56vEcv3kJxYt39A==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyM0F1QUxmc01jdFdqN1V6
            TC8rTi84eTRKNEE1ekVyMk1qSmNZQU0vYm5VCnZXSDBaZmpRbGVuTEhjTlBSR1RT
            MFVaRFJtNkFiejZ3aVRrbHVhckYyMk0KLS0tIFk1bk9IOFZCMU1IaHh1Vi9wb3hX
            ZG1mc0lNZVhPbTc4R0hBdFBjYXRqU0EKx3+8DqnUPdCaukdkjzJ5mVovXrFLGth8
            7Z3ZXmi21+52UVoEp4oMBpzRtOGBim7PAHvhjkyVD9Oe3QSTTN509w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T04:10:39Z"
    mac: ENC[AES256_GCM,data:dEKs3d8simwMiqkMt4Dw/Csuz8lw7kGqvbeRyVDbAvcvJIYE1O4Rco6L25/lP5Yk2YqoV4VWEofS+hFT/BJbN7Wn1bkkIDX8sLkdlwZjjp0n4+WHAoZbKsvqxKJh6cCq0+CUsrCoYGgpWXwTjQdof1ZA34a3Hvic+PduUsEABxY=,iv:HCUPSf3gjG4gu8XvlMGu0byhOkYpsabHgiBlY2DOfSo=,tag:8C4Kh7YzY0m1aUneWlfjww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
