apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: outline
resources:
  - postgres.yaml
  - dragonfly.yaml
  - persistentvolumeclaim.yaml
  - secret.sops.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
