apiVersion: v1
kind: Secret
metadata:
    name: outline-secret
    namespace: outline
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:EFfxoBk48O513pTqD2d1yfcWFvX5NK7LmzlZfNAtW0RL1oY6Kbx/excbmJQi0s16Eh5h4WhMfFhIaK2WH2+K5Q==,iv:s3AGkJw+ODcB7pW+rDA1g7/0MK3aqC0CmZs+qiOyQa8=,tag:cJeEZlncl4jVuTzemuC0Ig==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:X2q6kfFqY2hkK3/0i3wGivdKEs9INEwZLHKx3m5oG0vtjQ+YbleLZR1VhQt7XoPdKbbag2t5AqwFx/6kCnIGig==,iv:2g0DX1YvT5J6R5UnuqnnzVDJYAGsH024zzlKn1DSUpw=,tag:pxT0G9MfYwy7VpZRzk0qWA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:nRICYgPFtrS09hXO0EOtovVajbNcVFiVsEvMtgP1REKIeQ3i,iv:hcryL9Z3OTbYYKG0MpACcjEGDQXahRWjQA1tcTajc5g=,tag:c5/GB9bxry85HLAH7Da0uA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:kSs5NGRNtJHaGE2TvKAx40aH0syKJ67WF1t3ymauXxQ=,iv:8aTejKCmL9BM0OPHqU5AbDUje4fWKUFP3RF4U2w3iGc=,tag:VDyTIiVETV4cnaoxrJyG3A==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZmJmNVdJM0t1TzQ5dXpr
            VEhQbVg5M0dPSDU2ODRwUmJrVHJmYXBTZ20wCjI3dGZNMWJDMXBTNmhsUnhpck81
            ZVgrQWFMV0hMd3dDV2NGSm1yWWhFSTgKLS0tIGJEOFpUWTcwV1RrQzcycG92YUlJ
            TExFWlorMXZNWFBDL1ZWcEpJK3M0aGcKkJRkTDyQj3+GTTVR15GiRQ76yCVrq4qb
            FirBr/1LYXgeJjqtUKL3+Ubse72qamlxYL+X5FjHHxCLMrAfEnQgGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T19:40:48Z"
    mac: ENC[AES256_GCM,data:3WhcK7x/tfFTZNe7/YJ5CRtfY+omF4n704qffkU5u4PfQ5A33Z0fHt3OvXeBExMT7WOuesX82VBoUSMrkfdo5ab88O9xMWfYk6f7/IBDd3x4jIVcGRcJAR9iU98YXpxduZJoL8I8a9Jym5vWUoWWbAzQp/SSZaL3q9mCXX+kXCQ=,iv:YvFT7DPuKET93IwNpAtC/6ZRbcb7D1xJ7oRw7jYBhj4=,tag:V+fjmkhQ5+HoLZXvhAT7Xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
