apiVersion: v1
kind: Secret
metadata:
    name: gluetun-vpn-secret
    namespace: media
type: Opaque
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:cf/ELmNUOKw=,iv:mO1ZGd+47hF/EvqSTaFsRCzHvsECWI7IS7EQ8hV7UFc=,tag:EuOCQ8kSsoBWSfIGPxt2Sg==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:PvksYd4P4ocRSg==,iv:vli4M5ev+K0I+LflRrL7iYwQlJA09ddgIv3UseTu8Es=,tag:eECyL+UtsXVniU2uY4qqEA==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROWpRQWpuVWZ0QmRZcjF5
            M1V6akNZSkxaWWM2dmpSM3N5UWdhVlZjclRrCnBjWFFOdHU0SW45QWVyQ2V0NThq
            eTBpdnNoMDhVN0w2Mlk3SzE3K3VmY1kKLS0tIFoxNStobGQrS3prR3B2VXlSbGpu
            Nm5MN1JJbXcwRDZKcExXdFV3c0lFOEkKzwvw/nwziyf7k0X2LNbU5/AjLNmQT4kl
            NoTBh2J12Z20DMnSxYI1eF7YfxgSt8/rmGIAyWR6cuFiN7t7KHBCcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T05:36:00Z"
    mac: ENC[AES256_GCM,data:X51nGyYP6ybcQ/7DXTA6XDDcIlzzoDsjBhT9G9IU9nugzdYsz7ABXlj9oapxR9ae4ffUreJD7wYIt6/EEMFPD93lao8jKzFmR+WCWa/v/d4axY7dT6K3d/MaZJifa/eAZuc+tw8cvJZQh/yEbeNKu2rAEPFlyYApr4R4EKlXapo=,iv:r55ZKaDIuAl8yEHZrmX07F5p1p5bA8Cs/7cA49vnGrY=,tag:mxQ3SqnaM7LRNAYwGArgBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
