---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - deployment.yaml
  - services.yaml
  - httproutes.yaml
  - pvcs.yaml
  - persistentvolumes.yaml
  - gluetun-secret.yaml
