---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arch-delugevpn-data-pvc
spec:
  storageClassName: smb-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arch-delugevpn-config-pvc
spec:
  storageClassName: smb-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arch-jackett-data-pvc
spec:
  storageClassName: smb-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arch-jackett-config-pvc
spec:
  storageClassName: smb-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arch-sonarr-config-pvc
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arch-sonarr-media-pvc
spec:
  storageClassName: ""
  volumeName: arch-sonarr-media-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arch-radarr-config-pvc
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arch-radarr-media-pvc
spec:
  storageClassName: ""
  volumeName: arch-radarr-media-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
