apiVersion: v1
kind: Secret
metadata:
    name: birdnet-mqtt-timescaledb-env-secret
data:
    TIMESCALE_CONN_STRING: ENC[AES256_GCM,data:eUJP/fZBAsVWa+aKyToCZeAL4VpThtJXPO0V/lG9ZmgMcjQhHlrQtEOudRtk8xeBYCjM5pOlDqpFxxm0uXcEfKySEAqBO5AOyb2UWestKp1Z3tKGrY9MUMlvt5x4B8dA,iv:sSi+ES7EAE3OzIdPStdt9Av99zxfWzl177VygHt48q8=,tag:sW6ZMziQohAjDcmGCUqTfg==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTWd6UXArWWxGTFZ5MTdh
            N1I2MElYTmtGaXV6aDlOVjExbERGcStnZ25jCkRaYXdGMHV5WUY5enJENkZYOUpB
            eDB6QjJLOGg2SjVzTWx1MjlJUExnZkkKLS0tIG1YSzNqOUU1R29QOTlkL0ZYU09X
            elM5TVdOOGxKVHgxZ2xqbGp5dFlkMlUKcwpVCO6F9RCVYUh3+Ikmg1brOGX7WQX2
            VCHx38xa1T2t5vGP+IXt9mOoVPLKUhBKg/IAOxWcjM4kgPBD3WCERQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T17:04:47Z"
    mac: ENC[AES256_GCM,data:iVDKl5mQYbIsK4Ynd1EDG+PbAJEobUnnGeI644IVYukn+qFuy5cz1MbG4KhfcjbMgte07RkPOYZ0fBK4TLIpuza3NAEgkfKOdMe++p3+CEJZ/w0IA7EGCRnBG1ZBqQ54HpAA4udGWATkEbYmSbqVt/N4kfo/NmrduuhNdSXezGw=,iv:N0vh12yZh2qWsnH1bUZeLCi9HQL+jFpg9Iv0rNmiGfY=,tag:HROpKTSPr1/qkPZOyieWbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
