# MQTT broker address (LAN host) — kept out of the ConfigMap, injected via envFrom.
apiVersion: v1
kind: Secret
metadata:
    name: birdnet-mqtt-timescaledb-mqtt-secret
    namespace: birdnet
type: Opaque
stringData:
    MQTT_ADDRESS: ENC[AES256_GCM,data:U0NQjRxpYjPNUS81qIk=,iv:21fwJuWbSjQHOKXpNAsEs8IcGzRZz0ockwGOL7bZQIA=,tag:c+Dy4Z9GINqiZ4yLBJeifw==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSGJzZ3ZYVytEWWhSNkdV
            T3NqMTAvZTJud1JXY0FIUHNUNDBIYUp5WXg4CjZpdkdBN2QrM0MzRndZS2lrSE5t
            T051NDdzUnI4ekdiVWg0SUo4TFdySVUKLS0tIDFFL2xGQWV0NWFpbUZZTUxLYkpy
            Tk9SeFhwNjA1SFA2VmVGbDZRVzhsejAKT9GNv8nvebcLRj0bh1yLWQxFAlAZKyAA
            oL5+1lmGhH68v1Jjpoeg9WvEW9rQD8qqvRGD3x0fDXxqAijICtIJSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T08:02:23Z"
    mac: ENC[AES256_GCM,data:vN5xrtcHI/AItQRg+cgc85ibFjQ69VcB+vOA/jFyTEmqPXGdQIiXb9gAWhQjiiChHhBSB4CmtH0dCs+Q1fNmagXjK+MkEucRTaw/6Vf41WC4yFg/Y6EHhgflofe8MQePDya4G9deZBUpbWRL/7eRGDBMIZRzivSPiu3wj5APkrE=,iv:g2LPJR1hxkVGWo2yyGmWV7rDc3dPWMLaV5/NNcMtNHI=,tag:RhzoGBJDtmvsLOmucO6PFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
