---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lfpweather-frontend-env-configmap
data:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name lfpweather-frontend
  labels:
    app: *name
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.istio.io/merge-metrics: "false"
    spec:
      containers:
        - name: *name
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: lfpweather-frontend-env-configmap
            - secretRef:
                name: lfpweather-frontend-env-secret
          ports:
            - name: frontend
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /about
              port: frontend
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /about
              port: frontend
            periodSeconds: 5
          resources:
            limits:
              memory: "1Gi"
            requests:
              cpu: "50m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: lfpweather-frontend
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lfpweather-frontend-httproute
