---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webcam-scraper-env-configmap
data:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name webcam-scraper
  labels:
    app: *name
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      containers:
        - name: *name
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: webcam-scraper-env-configmap
            - secretRef:
                name: webcam-scraper-secret
          ports:
            - name: metrics
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: metrics
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
            requests:
              cpu: "20m"
              memory: "128Mi"
