---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webcam-scraper-pv
  namespace: webcam-scraper
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webcam-scraper-pvc
  namespace: webcam-scraper
