---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adsbx-live-notifier-env-configmap
data:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name adsbx-live-notifier
  labels:
    app: *name
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.istio.io/merge-metrics: "false"
    spec:
      containers:
        - name: *name
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: adsbx-live-notifier-env-configmap
            - secretRef:
                name: adsbx-live-notifier-env-secret
          ports:
            - name: metrics
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: metrics
            periodSeconds: 5
          resources:
            limits:
              memory: "128Mi"
            requests:
              cpu: "20m"
              memory: "32Mi"
          volumeMounts:
            - name: watchlist
              mountPath: /etc/adsbx
              readOnly: true
      volumes:
        - name: watchlist
          configMap:
            name: adsbx-live-notifier-watchlist
