apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secrets
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:HwGHBt7pYbdu5ZwE6FykF6HKVl6DQFntEY7rsrdne/XSKCpY,iv:YxUoq8m/x/XI+Xe6a4wZIAJx79T1bfYkfh8qOYkVxfw=,tag:1nNbshCXAzOo/Kdqy/PgZw==,type:str]
    client-secret: ENC[AES256_GCM,data:9BcSxQahuU2LyOmoasjilS6paeqlrkMqo/kpWWxe0/g=,iv:BBt9DLe0fjkv+SaNVA7VFvbXA/XJtVFee7y6ql2I+o8=,tag:AI5p81i9SCaLq8ZeAgg7Ig==,type:str]
    cookie-secret: ENC[AES256_GCM,data:p0y2mCsnFp2fJfqZ/bVykcShe7Kb6vbw8jIXkzy0ZZE=,iv:etVbCS8k5PVMK8UenPC4sJ//OxKGyD3L0A1shuTWgTk=,tag:9qRSrS/OGm6Pm24YuxXauw==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQUpUeTd6RDdHN200Slll
            eW4vNjduVlZoTXpiU2orZGpKM0tmNGtxNTNJClVnK3FMSkNIRzM0eEd0Y3JkZG1t
            bkUxRnFWVW5xZkdZcmxxNjNLbmZBSjQKLS0tIGRCYnNlMGdnZ1U3bEhyZkZKeEFm
            R0IvMkNXMFhtd2wzVzBwZ3lLQVp5MGMKiIUXhdrw3Yf03UuYia+mmhrBv+Yu2zb8
            EdKp/QD6UvxcW1iPAiDAYG1jdP/JPdm65y/y3EStu0HsG/WHj8gDMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T04:59:32Z"
    mac: ENC[AES256_GCM,data:xALqwjfI8noy80pH7IlFOVQV/QeWLqE2RbcdG8e+I7S/2XvyN/lGlQZMYwZy1nd0WWks3otRxih4YiYm00WFCg03ybaiS4/RPTPPLfHK+s/S3nogibustT3Gctadpd9xebcWZ4iqle7tLhTxo1s9JkaAMBxKN7LiUi9nL+bsXDk=,iv:fYBo71mKUmlAx+5gSUM/5Hql7LVkD8eZ5Z/NJifFbkU=,tag:QOKbVcLGRZNWM/MfC/ZhDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
