---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webcam-scraper-env-configmap
data:
  # logging
  LOG_LEVEL: "info"
  CRON_SCHEDULE: "*/5 * * * *"

  # yamllint disable-line rule:line-length
  DOMAINS: "shorecrest-weatherbug-scrape:https://www.weatherbug.com/weather-camera/?cam=SHRST,openwindowschool-weatherbug-scrape:https://www.weatherbug.com/weather-camera/?cam=BLVPW,overlakeschool-weatherbug-scrape:https://www.weatherbug.com/weather-camera/?cam=RDVRL,lakeforestpark-wsdot-api:1202,kenmore-wsdot-api:1498,bothell-wsdot-api:9077,woodinville-wsdot-api:9291,sunmountain-sunmountainlodge-scrape:https://sunmountainlodge.com/webcam/,mazama-direct-direct:http://mazamacam.earthandskystudios.com/content/ranchhouseimg.jpg,winthrop-direct-direct:http://highlandmeadow.homelinux.org/"
  OUTPUT_IMAGE_DIR: "/images"

  # metrics
  METRICS_ENABLED: "true"
  METRICS_PORT: "8081"

  # tracing
  TRACING_ENABLED: "false"
  TRACING_SAMPLERATE: "1.0"
  TRACING_SERVICE: "webcam-scraper"
  TRACING_VERSION: "0.0.1"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo:4317"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name webcam-scraper
  labels:
    app: *name
spec:
  selector:
    matchLabels:
      app: *name
  revisionHistoryLimit: 10
  replicas: 1
  template:
    metadata:
      labels:
        k8s.lfp.rocks/service: "webcam-scraper"
        k8s.lfp.rocks/version: "v1.0.1"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: k8s.lfp.rocks/gpu
                    operator: NotIn
                    values:
                      - enabled
      containers:
        - name: *name
          image: ghcr.io/michaelpeterswa/webcam-scraper:v1.0.1
          volumeMounts:
            - mountPath: /images
              name: webcam-scraper-pvc-volume
              subPath: "webcam-scraper"
      volumes:
        - name: webcam-scraper-pvc-volume
          persistentVolumeClaim:
            claimName: webcam-scraper-pvc
