apiVersion: v1
kind: Secret
metadata:
  name: webcam-scraper-secret
data:
  WSDOT_API_KEY: ENC[AES256_GCM,data:LxAQYfe32Ah1ZWVKgtzcD2ZwsnKGLQTdtKvDmovNV0VAYvAgK2bEYw2vYNIjkCjK,iv:m5LIVrJe43c7CkeuJwqbJqxtFEjQ2VNh4qGVisGnY2Y=,tag:dy0oP0ks1apkH4JAlsURyQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b1F3ZmsyNDUzcndQTjVm
        SVRJRXRmckc0U3ZIaFA2aFFZWnVPTTZVQUJzCjBkV1ZxS0Fta0JxY1V6ekh4WVdx
        NnQ5ZG1QODZuM3VUMlBlNkhpYXk3TmcKLS0tIFk0SVhkVFYzSXVCOWV3UEhKSWVO
        aDU3Rkx6MnlvcU5ERDBNcnhuQlNncVkKoSjiiJ8IeHhzsEQlppwF1lefNeEnhZJt
        XqRSXyB7/7F1gsPDIo2GdIXkmATeRMiWSnE0OLzrJQbtI9z8fde1qA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-31T19:49:29Z"
  mac: ENC[AES256_GCM,data:OsbWkneQqpernYbUjueDulSg4ueHnzDJFSTpJOpK+HByLRpfAFd9aEOC5LJDyPsY3G270uxjAqgF6h3uwXRCkA7GJmk5jJ5ulxhIsNIVjIrnChnKRR8ouuxwNcZM0xNzZia5k3JLucPucPGYpGn5DfBQiTwWRIT9tG2mvJLXiXw=,iv:WDkphTzELp06rAt3czVvSLEQ39hg3jRtmEKW6C7cjig=,tag:tMI12GUQVsIATJ4YxINncA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
