# Sensitive Helm values for emqx, merged via valuesFrom (deleted from inline spec.values).
# Encrypted with SOPS. Dashboard default password — rotate before going public.
apiVersion: v1
kind: Secret
metadata:
    name: emqx-values-secret
    namespace: emqx
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:lXYICiQpeVUEwf76QrKxfn2y3D9n3WpggpMWdk91h7Tz06o3PbBhxjnOrkuDAybHeUGqLul6h1qY,iv:vLjsvXlTAsOCRi4eEFRTEOW868l9x+eVlXsofiOkvFc=,tag:Ii/iUE8GnNVY6kdr066LBg==,type:str]
sops:
    age:
        - recipient: age123w4afwqywmqdvkvlmdm8nqwv7a4jl2mgx6alu2phpa4qnsk6cuq4p0gas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQjhkZzlBdmowbVRXWk81
            cHdLMTVSZ0hhM0xqUVY3bVU4SittaGo2V1RNCnRwcXhWY0w3YThkci9Oa2pyc1Bi
            Tzg5RUVYLy8zYW9xWldTNTM3UkQyL2cKLS0tIHY1em1DOHlWVmJiZnRhMXpwS3gw
            dWNwQ2tPTkMyRWpFTmt4M0N0VUhDWlEKj9kcQDZLYJLYwlA6pQgM2AzFrPkVjrww
            wvwVaN916lHctrikzpVRnovmikFxz+3ZspxGMAALhlZUj9VrK9TJpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T07:29:10Z"
    mac: ENC[AES256_GCM,data:7butD3DUIbZSJYUNdR/aK7AncoYl0KqM/mz7y96U+U+qqOCjjT4e3YoQPmv6M0oDrCsc+s/wMnJ6P2ERez07r+me0UQtT7BmRFTav1Oo1CI4lLjigKWapDSAVxig/Sn2tAeBrUG00yMjAnQ1Q0YRx9RGqkGWNsvbkHoAScdfnNE=,iv:on4aEOEZ3rzKGqc/pnVbiGoHRBTSnfMUPqFVZuuWxls=,tag:j3mw0GLDEU5RtgtRw6a9RA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
